#!/usr/bin/env bash
################################################################################
export SW_USE_LAUNCH_PARAMETERS="--launch-product=league_of_legends" "--launch-patchline=live"
export SW_USE_WINEDLLOVERRIDES=""
export SW_USE_WINEARCH="win64"
export SW_USE_WINDOWS_VER="10"
export SW_USE_REGEDIT_PATCH=""
export SW_USE_DXVK_GE=0
export SW_USE_VKD3D_GE=0
export SW_USE_OPENGL=0
export SW_USE_STRANGLE_FPS_LIMIT=0
export SW_USE_MANGOHUD_DLSYM=0
export SW_USE_MANGOHUD=1
export SW_USE_GAMEMODE=1
export SW_USE_RUNTIME=1
export SW_USE_RESTORE_RESOLUTION=0
export SW_USE_VIRTUAL_DESKTOP=0
export SW_USE_FSYNC=0
export SW_USE_ESYNC=0
export SW_USE_OLD_GL_STRING=0
export SW_USE_NVAPI_DISABLE=0
export SW_USE_WINEDBG_DISABLE=1
export SW_USE_LARGE_ADDRESS_AWARE=1
export SW_USE_STAGING_WRITECOPY=0
export SW_USE_STAGING_SHARED_MEMORY=1
export SW_USE_DXVK_HUD=0
export SW_USE_DXVK_ASYNC=1
export SW_USE_ENABLE_VKBASALT=1
export SW_USE_FSR=1
export SW_USE_GSTREAMER=1
export SW_USE_DRI_PRIME=0
export SW_USE_WINE_MONO=1
export SW_USE_BATTLEYE=0
export SW_USE_EASYANTICHEAT=0
export SW_USE_D3D_PLUGINS=0
export SW_USE_VSYNC_DISABLE=0
export SW_USE_HIDE_NVIDIA_GPU=0
export SW_USE_LANG=ru
export SW_USE_THEME=blue
export SW_USE_VKBASALT_EFFECTS="cas:Tonemap:Colourfulness:"
export SW_USE_VKBASALT_CAS="0.6"
export SW_USE_HUD_POSITION="R"
export SW_USE_FPS_LIMIT="0.0"
export SW_USE_MANGOHUD_CONFIG=",core_load,gamemode,vkbasalt,resolution,wine,arch,version,time,vram,ram,gpu_core_clock,gpu_temp,cpu_mhz,cpu_temp,"
export SW_USE_WINE="wine_custom/lutris-ge-lol"
export SW_USE_PFX="pfx_RiotClientServices"
################################################################################

check_lol () {

    process=LeagueClientUx.exe
    while [[ -z `pidof ${process}` ]] ; do
        echo "PID ${process} not found"
        sleep 1
    done
    uxpid=`pidof ${process}`
    echo "LeagueClientUx pid: ${uxpid}"
    port=$(xargs -0 < /proc/${uxpid}/cmdline | sed -n 's/.*--app-port=\([[:digit:]]*\).*/\1/p')

    if [ ! -n $port ]; then
        echo "Could not find port"
        exit 1
    fi

    echo "Waiting for port ${port}"
    kill -STOP ${uxpid}
    timeout 200m /bin/bash -c "
    until openssl s_client -connect :${port} <<< Q > /dev/null 2>&1 ; do
    sleep 1
    done"
    kill -CONT ${uxpid}

}

add_in_start () {

    if [ "$(cat /proc/sys/abi/vsyscall32)" -ne 0 ]; then
        pkexec /bin/bash -c 'sysctl -w abi.vsyscall32=0 && sysctl -p'
    fi

    check_lol &

}

#add_in_start

################################################################################
