#!/usr/bin/env bash
################################################################################
export LAUNCH_PARAMETERS="--launch-product=league_of_legends" "--launch-patchline=live"
export WINEDLLOVERRIDES=""
export WINEARCH="win64"
export SW_WINDOWS_VER="10"
#export DXVK_GE=1
#export VKD3D_GE=1
#export USE_OPENGL=1
#export SW_STRANGLE_FPS_LIMIT=1
#export SW_FPS_LIMIT="60"
export SW_HUD_POSITION="R"
#export SW_MANGOHUD_DLSYM=1
export SW_MANGOHUD=1
export RUN_GAMEMODE=1
export RUN_RUNTIME=1
#export RESTORE_RESOLUTION=1
#export VIRTUAL_DESKTOP=1
export SW_FSYNC=1
export WINEESYNC=1
#export OLD_GL_STRING=1
#export NVAPI_DISABLE=1
export WINEDBG_DISABLE=1
export WINE_LARGE_ADDRESS_AWARE=1
#export STAGING_WRITECOPY=1
export STAGING_SHARED_MEMORY=1
#export DXVK_HUD=1
export DXVK_ASYNC=1
export SW_ENABLE_VKBASALT=1
export SW_FULLSCREEN_FSR=1
export SW_GSTREAMER=1
#export SW_DRI_PRIME=1
export WINE_MONO=1
#export SW_BATTLEYE=1
#export SW_EASYANTICHEAT=1
#export SW_D3D_PLUGINS=1
#export SW_VSYNC_DISABLE=1
SW_THEME=green_theme
export VKBASALT_EFFECTS="cas:Tonemap:Colourfulness:"
#export VKBASALT_CAS="0"
export SW_WINE_USE="wine_custom/lutris-ge-7.0-lol"
export PFX_GAME="pfx_RiotClientServices"
################################################################################

check_lol () {

    process=LeagueClientUx.exe
    while [[ -z `pidof ${process}` ]] ; do
        echo "PID ${process} not found"
        sleep 1
    done
    uxpid=`pidof ${process}`
    echo "LeagueClientUx pid: ${uxpid}"
    port=$(xargs -0 < /proc/${uxpid}/cmdline | sed -n 's/.*--app-port=\([[:digit:]]*\).*/\1/p')

    if [ ! -n $port ]; then
        echo "Could not find port"
        exit 1
    fi

    echo "Waiting for port ${port}"
    kill -STOP ${uxpid}
    timeout 200m /bin/bash -c "
    until openssl s_client -connect :${port} <<< Q > /dev/null 2>&1 ; do
    sleep 1
    done"
    kill -CONT ${uxpid}

}

add_in_start () {

    if [ "$(cat /proc/sys/abi/vsyscall32)" -ne 0 ]; then
        pkexec /bin/bash -c 'sysctl -w abi.vsyscall32=0 && sysctl -p'
    fi

    check_lol &

}

add_in_start

########################################################################################################################
