#!/usr/bin/env python3

import os

from Xlib import display as xdisplay

try:
    mhfratio = int(os.getenv('MANGOHUD_FONT_SIZE_RATION'))
except:
    mhfratio = 55

MANGOHUD_FONT_SIZE_RATION = mhfratio

display = xdisplay.Display()
root_screen = display.screen().root

for mon in root_screen.xrandr_get_monitors().monitors:
    if mon.primary:
        connector = display.get_atom_name(mon.name)
        print(int(mon.height_in_pixels / MANGOHUD_FONT_SIZE_RATION))
