#!/bin/bash

cd "$(dirname "`readlink -f "$0"`")"
export link="$(pwd)"
cd "${link}/../../"
export START_WINE_PATH="$(pwd)"

###############################   TOOLS   ######################################

export SW_NAME="StartWine-Launcher"
export SW_VER=" v3.5.1"
export GE_VER="7-10"
export SP_VER="7.0.1"
export STAG_VER="7.4"
export LUTRIS_VER="7.2"
export LUTRIS_GE_VER="7-7"
export DXVK_VER="1.10"
export VKD3D_VER="2.6"
export UTILS_VER="v0.8"
export ANTICHEAT_VER="v0.1"
export SW_UPDATE_TIME=14
export DEFAULT_WINE="wine_steam_proton"
export SCRIPTS="${START_WINE_PATH}/data/scripts"
export CRIER="${SCRIPTS}/sw_crier"

##############################   FUNCTIONS TOOLS   #############################

print_error () {

    echo "ERROR: $@"

}

print_info () {

    echo "INFO: $@"

}

try_copy_file () {

    if [ ! -f "$1" ]; then
        print_info "file $1 not found for copy" && return 1
    elif [ -z "$2" ]; then
        print_error "no way to copy file $1" && return 1
    else
        cp -f "$1" "$2"
        if [ "$?" != 0 ]; then
            print_error "failed to copy file $1 to $2" || return 1
        else
            print_info "copy file $1 to $2 was successful" || return 0
        fi
    fi

}

try_copy_dir () {

    if [ ! -d "$1" ]; then
        print_info "directory $1 not found for copy"
    elif [ -z "$2" ]; then
        print_error "no way to copy directory $1"
    else
        cp -fr "$1" "$2"
        [ "$?" != 0 ] && print_error "failed to copy directory $1 to $2" || return 0
    fi
    return 1

}

try_force_link_file () {

    if [ ! -f "$1" ]; then
        print_info "file $1 not found for link"
    elif [ -z "$2" ]; then
        print_error "no way to link file $1"
    else
        ln -sf "$1" "$2"
        [ "$?" != 0 ] && print_error "failed to link file $1 to $2" || return 0
    fi
    return 1

}

try_force_link_dir () {

    if [ ! -d "$1" ]; then
        print_info "directory $1 not found for link"
    elif [ -z "$2" ]; then
        print_error "no way to link directory $1"
    else
        ln -sf "$1" "$2"
        [ "$?" != 0 ] && print_error "failed to link directory $1 to $2" || return 0
    fi
    return 1

}

create_new_dir () {

    if [ ! -d "$1" ]; then
        mkdir -p "$1"
    fi

}

try_remove_file () {

    if [ -f "$1" ]; then
        rm -fr "$1"
        [ "$?" != 0 ] && print_error "failed to remove file $1" || return 0
    fi
    return 1

}

try_remove_dir () {

    if [ -d "$1" ]; then
        rm -fr "$1"
        [ "$?" != 0 ] && print_error "failed to remove directory $1" || return 0
    fi
    return 1

}

try_remove_steam_lib () {

rm -fr "${WINEDIR}/share/default_pfx"
rm -fr "${WINEDIR}"*/lib*/*steam*
rm -fr "${WINEDIR}"*/lib*/wine/*steam*
rm -fr "${WINEDIR}"*/lib*/wine/*/*steam*

}

var_winedlloverride_update () {

    if [ ! -z "${WINEDLLOVERRIDES}" ]; then
        export WINEDLLOVERRIDES="${1};${WINEDLLOVERRIDES}"
    else
        export WINEDLLOVERRIDES="${1}"
    fi

}

var_ld_library_path_update () {

    if [ ! -z "${LD_LIBRARY_PATH}" ]; then
        export LD_LIBRARY_PATH="${1}:${LD_LIBRARY_PATH}"
    else
        export LD_LIBRARY_PATH="${1}"
    fi

}

var_winedllpath_update () {

    if [ ! -z "${WINEDLLPATH}" ]; then
        export WINEDLLPATH="${1}:${WINEDLLPATH}"
    else
        export WINEDLLPATH="${1}"
    fi

}

var_path_update () {

    if [ ! -z "${PATH}" ]; then
        export PATH="${1}:${PATH}"
    else
        export PATH="${1}"
    fi

}

try_clear_pfx () {

    rm -rf "$WINEPREFIX/registry_"*
    rm -rf "$WINEPREFIX/"*.reg
    rm -rf "$WINEPREFIX/"*.log
    rm -rf "$WINEPREFIX/.update-timestamp"
    rm -rf "$WINEPREFIX/drive_c/.windows-serial"
    rm -rf "$WINEPREFIX/drive_c/windows/"
    rm -rf "$WINEPREFIX/drive_c/ProgramData/Setup"
    rm -rf "$WINEPREFIX/drive_c/ProgramData/Windows"
    rm -rf "$WINEPREFIX/drive_c/ProgramData/WindowsTask"
    rm -rf "$WINEPREFIX/drive_c/ProgramData/Package Cache"
    rm -rf "$WINEPREFIX/drive_c/users/Public/Local Settings/Application Data/Microsoft"
    rm -rf "$WINEPREFIX/drive_c/users/Public/Local Settings/Application Data/Temp"
    rm -rf "$WINEPREFIX/drive_c/users/Public/Local Settings/Temporary Internet Files"
    rm -rf "$WINEPREFIX/drive_c/users/Public/Application Data/Microsoft"
    rm -rf "$WINEPREFIX/drive_c/users/Public/Application Data/wine_gecko"
    rm -rf "$WINEPREFIX/drive_c/users/Public/Temp"
    rm -rf "$WINEPREFIX/drive_c/users/user/Local Settings/Application Data/Microsoft"
    rm -rf "$WINEPREFIX/drive_c/users/user/Local Settings/Application Data/Temp"
    rm -rf "$WINEPREFIX/drive_c/users/user/Local Settings/Temporary Internet Files"
    rm -rf "$WINEPREFIX/drive_c/users/user/Application Data/Microsoft"
    rm -rf "$WINEPREFIX/drive_c/users/user/Application Data/wine_gecko"
    rm -rf "$WINEPREFIX/drive_c/users/user/Temp"
    rm -rf "$WINEPREFIX/drive_c/Program Files/Internet Explorer"
    rm -rf "$WINEPREFIX/drive_c/Program Files/Windows Media Player"
    rm -rf "$WINEPREFIX/drive_c/Program Files/Windows NT"
    rm -rf "$WINEPREFIX/drive_c/Program Files/Common Files"
    rm -rf "$WINEPREFIX/drive_c/Program Files (x86)/Internet Explorer"
    rm -rf "$WINEPREFIX/drive_c/Program Files (x86)/Common Files"
    rm -rf "$WINEPREFIX/drive_c/Program Files (x86)/Windows Media Player"
    rm -rf "$WINEPREFIX/drive_c/Program Files (x86)/Windows NT"
    rm -rf "${START_WINE_PATH}/data/tmp/gl_shader_cache/"*
    rm -rf "${START_WINE_PATH}/data/tmp/log/"*
    rm -rf "${START_WINE_PATH}/data/tmp/"*.log
    rm -rf "${START_WINE_PATH}/data/tmp/dxvk_cache/"*
    rm -rf "${START_WINE_PATH}/data/tmp/gstreamer-1.0/"*
    rm -rf "$HOME/.cache/gstreamer-1.0/"*
    rm -rf "${START_WINE_PATH}/data/tmp/mesa_shader_cache/"*

}

prefix_init_error () {

    clear
    echo "There is a problem initializing the Wine prefix !"
    try_clear_pfx
    crier=`$CRIER -e "Error initializing the Wine prefix"`
    exit 1

}

libraries_init_error () {

    clear
    echo "Error installing libraries, try again !"
    try_clear_pfx
    crier=`$CRIER -e "Error installing libraries, try again"`
    exit 1

}

wait_wineserver () {

    sleep 1
    while [ ! -z "$(ls -l /proc/*/exe 2>/dev/null | grep -ie ${SW_NAME} | grep -E 'wine(64)?-preloader|wineserver' | awk -F/ '{print $3}')" ]; do
        sleep 1
    done

}

sw_win_ver () {

    if [[ -z `cat "${WINEPREFIX}/system.reg" | grep "Windows $SW_WINDOWS_VER"` ]]; then
        if [ ! -z "${SW_WINDOWS_VER}" ] && [ `echo "$SW_WINDOWS_VER" | sed 's/.*/\L&/'` == "xp" ]; then
            if [ "${WINEARCH}" != "win32" ]; then
                export SW_WINDOWS_VER="xp64"
            else
                export SW_WINDOWS_VER="xp"
            fi
        fi
        ${SW_RUNTIME} env "${WINELOADER}" winecfg -v `echo "win${SW_WINDOWS_VER}" | sed 's/.*/\L&/'`
        echo "Set to win${SW_WINDOWS_VER}"
        wait_wineserver
    fi

}

try_fix_pfx () {

    if [ ! -d "${START_WINE_PATH}/data/pfx/${PFX_GAME}/drive_c/users/${USER}" ]; then
        try_force_link_dir "${START_WINE_PATH}/data/pfx/${PFX_GAME}/drive_c/users/steamuser" "${START_WINE_PATH}/data/pfx/${PFX_GAME}/drive_c/users/${USER}"
    fi

    if [ ! -d "${WINEPREFIX}/drive_c/users/steamuser/My Documents" ]; then
        try_force_link_dir "${WINEPREFIX}/drive_c/users/steamuser/Documents" "${WINEPREFIX}/drive_c/users/steamuser/My Documents"
    fi

    if [ ! -d "${START_WINE_PATH}/data/pfx/${PFX_GAME}/drive_c/Games" ]; then
        try_force_link_dir "${START_WINE_PATH}/Games/" "${START_WINE_PATH}/data/pfx/${PFX_GAME}/drive_c/Games"
    fi

    if [ ! -d "${WINEPREFIX}/drive_c/users/Public/Documents/Steam" ]; then
        create_new_dir "${WINEPREFIX}/drive_c/users/steamuser/Documents/Steam"
        create_new_dir "${WINEPREFIX}/drive_c/users/Public/Documents/Steam"
        create_new_dir "${WINEPREFIX}/drive_c/windows/Fonts"
        try_force_link_file "${WINEDIR}/share/fonts/"LiberationSans-Regular.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"arial.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"LiberationSans-Bold.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"arialbd.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"LiberationSerif-Regular.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"times.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"LiberationMono-Regular.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"cour.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"LiberationMono-Bold.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"courbd.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"msyh.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"msyh.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"malgun.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"malgun.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"micross.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"micross.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"nirmala.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"nirmala.ttf
        try_force_link_file "${WINEDIR}/share/fonts/"simsun.ttc "${WINEPREFIX}/drive_c/windows/Fonts/"simsun.ttc
        try_force_link_file "${WINEDIR}/share/fonts/"msgothic.ttc "${WINEPREFIX}/drive_c/windows/Fonts/"msgothic.ttc
        try_force_link_file "${WINEDIR}/share/wine/fonts/"tahoma.ttf "${WINEPREFIX}/drive_c/windows/Fonts/"tahoma.ttf

        chmod -R 775 "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    fi

}

sw_shortcuts_autoinstall () {

    try_fix_pfx

    STARTWINE_EXE="${WINEPREFIX}/${SW_USE_EXE}"
    STARTWINE_NAME="$(basename "${STARTWINE_EXE}" | sed 's/\.exe//gi' | sed 's/ /_/g')"
    STARTWINE_PATH="$(cd "$(dirname "${STARTWINE_EXE}")" >/dev/null 2>&1 && pwd)"

    if [ -x "`which wrestool 2>/dev/null`" ]; then
        cd "${STARTWINE_PATH}"
        wrestool -x -t14 "${STARTWINE_EXE}" > "${STARTWINE_EXE}.ico"
        icotool -x "${STARTWINE_EXE}.ico"
        cp "$(ls -S -1 "${STARTWINE_EXE}"*.png | head -n 1)" "${STARTWINE_EXE}.png"
        cp -f "${STARTWINE_EXE}.png" "${START_WINE_PATH}/data/img/${STARTWINE_NAME}.png"
        rm -f "${STARTWINE_PATH}/"*.ico
        rm -f "${STARTWINE_PATH}/"*.png
    fi

    convert -resize 256X256 "${START_WINE_PATH}/data/img/${STARTWINE_NAME}.png" "${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x256.png"
    convert -resize 96X96 "${START_WINE_PATH}/data/img/${STARTWINE_NAME}.png" "${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x96.png"
    rm -f "${START_WINE_PATH}/data/img/${STARTWINE_NAME}.png"

    name_desktop="${STARTWINE_NAME}"
    echo "[Desktop Entry]" > "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "Name=${STARTWINE_NAME}" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "Name_2=pfx_${STARTWINE_NAME}" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "Exec=env "\"${START_WINE_PATH}/data/scripts/start\" \"${STARTWINE_EXE}\"""\
    >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "Type=Application" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "Categories=Game" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "StartupNotify=true" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "Path="${START_WINE_PATH}/data/scripts/"" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "Icon="${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x256.png"" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    echo "SW_USE=""${SW_WINE_AUTOINSTALL}" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
    chmod +x "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"

    try_copy_file "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop" "${START_WINE_PATH}/data/img/favorites"

}

###############################   WINE   #######################################

export GAME_EXE="$(readlink -f "$1")"
export STARTWINE_EXE="${GAME_EXE}"
export STARTWINE_NAME="$(basename "${STARTWINE_EXE}" | sed 's/\.exe//gi' | sed 's/ /_/g')"
export STARTWINE_PATH="$(cd "$(dirname "${STARTWINE_EXE}")" >/dev/null 2>&1 && pwd)"
export name_desktop="${STARTWINE_NAME}"

if [ "$(sed -n '3p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop" | sed 's/Name_2=//g' | sed 's/ /_/g' | sed 's/[^pfx_].*//g')" == "pfx_" ]; then
    export PFX_GAME="$(sed -n '3p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop" | sed 's/Name_2=//g' | sed 's/ /_/g')"
else
    export PFX_GAME="pfx_default"
fi

export sw_custom_1="${START_WINE_PATH}/data/wine/wine_custom/`ls -1 | tail -n1 | head -n1`"
export sw_custom_2="${START_WINE_PATH}/data/wine/wine_custom/`ls -1 | tail -n2 | head -n1`"
export sw_custom_3="${START_WINE_PATH}/data/wine/wine_custom/`ls -1 | tail -n3 | head -n1`"
export sw_custom_4="${START_WINE_PATH}/data/wine/wine_custom/`ls -1 | tail -n4 | head -n1`"
export sw_custom_5="${START_WINE_PATH}/data/wine/wine_custom/`ls -1 | tail -n5 | head -n1`"

if [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE=wine_staging" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_staging/bin" ]; then
        crier=`$CRIER -i "Click the download wine button in the main menu and download wine staging"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_staging"
    fi
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE=wine_steam_proton" ]; then
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_steam_proton"
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE=wine_proton_ge" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_proton_ge/bin" ]; then
        crier=`$CRIER -i "Click the download wine button in the main menu and download wine proton ge"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    fi
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE=wine_lutris" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_lutris/bin" ]; then
        crier=`$CRIER -i "Click the download wine button in the main menu and download wine lutris"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
     else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_lutris"
    fi
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE=wine_lutris_ge" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_lutris_ge/bin" ]; then
        crier=`$CRIER -i "Click the download wine button in the main menu and download wine lutris ge"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_lutris_ge"
    fi
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE="${sw_custom_1}"" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_1}"/bin" ]; then
        crier=`$CRIER -i "Select custom wine in download wine menu, copy your wine to open directory"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_1}""
    fi
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE="${sw_custom_2}"" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_2}"/bin" ]; then
        crier=`$CRIER -i "Select custom wine in download wine menu, copy your wine to open directory"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_2}""
    fi
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE="${sw_custom_3}"" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_3}"/bin" ]; then
        crier=`$CRIER -i "Select custom wine in download wine menu, copy your wine to open directory"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_3}""
    fi
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE="${sw_custom_4}"" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_4}"/bin" ]; then
        crier=`$CRIER -i "Select custom wine in download wine menu, copy your wine to open directory"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_4}""
    fi
elif [ "$(sed -n '10p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop")" == "SW_USE="${sw_custom_5}"" ]; then
    if [ ! -d "${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_5}"/bin" ]; then
        crier=`$CRIER -i "Select custom wine in download wine menu, copy your wine to open directory"`
        export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    else
        export WINEDIR="${START_WINE_PATH}/data/wine/wine_custom/"${sw_custom_5}""
    fi
else
    export WINEDIR="${START_WINE_PATH}/data/wine/"${DEFAULT_WINE}""
    clear
fi

var_ld_library_path_update "${START_WINE_PATH}/data/tools/utils/libs/i386"
var_ld_library_path_update "${START_WINE_PATH}/data/tools/utils/libs/x86-64"
var_ld_library_path_update "${WINEDIR}/lib"
var_ld_library_path_update "${WINEDIR}/lib64"

var_winedllpath_update "${WINEDIR}/lib/wine"
var_winedllpath_update "${WINEDIR}/lib64/wine"
var_winedllpath_update "${WINEDIR}/lib/wine/i386-windows"
var_winedllpath_update "${WINEDIR}/lib/wine/x86_64-windows"
var_winedllpath_update "${WINEDIR}/lib64/wine/x86_64-windows"

var_path_update "${WINEDIR}/bin"

export WINELOADER="${WINEDIR}/bin/wine"
export WINESERVER="${WINEDIR}/bin/wineserver"
export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
export WINESTART_EXE="start.exe /i /unix"

##############################   SETTINGS   ####################################

if [ "$(sed -n '/001/p' "${SCRIPTS}/settings")" == "001_MANGOHUD_DLSYM" ]; then
    export SW_MANGOHUD_DLSYM=1
    echo "MANGOHUD_DLSYM  ON"
else
    echo "MANGOHUD_DLSYM  OFF"
fi

if [ "$(sed -n '/002/p' "${SCRIPTS}/settings")" == "002_MANGOHUD" ]; then
    export SW_MANGOHUD=1
    export SW_FPS_LIMIT="$(sed -n '25p' ${START_WINE_PATH}/data/scripts/settings)"
    echo "MANGOHUD  ON"
else
    export SW_FPS_LIMIT="$(sed -n '25p' ${START_WINE_PATH}/data/scripts/settings)"
    echo "MANGOHUD  OFF"
fi

if [ "$(sed -n '/003/p' "${SCRIPTS}/settings")" == "003_GAMEMODE" ]; then
    export RUN_GAMEMODE=1
    echo "GAMEMODE  ON"
else
    echo "GAMEMODE  OFF"
fi

if [ "$(sed -n '/004/p' "${SCRIPTS}/settings")" == "004_RUNTIME" ]; then
    export RUN_RUNTIME=1
    echo "RUNTIME  ON"
else
    echo "RUNTIME  OFF"
fi

if [ "$(sed -n '/005/p' "${SCRIPTS}/settings")" == "005_RESTORE_RESOLUTION" ]; then
    export RESTORE_RESOLUTION=1
    echo "RESTORE_RESOLUTION  ON"
else
    echo "RESTORE_RESOLUTION  OFF"
fi

if [ "$(sed -n '/006/p' "${SCRIPTS}/settings")" == "006_VIRTUAL_DESKTOP" ]; then
    export VIRTUAL_DESKTOP=1
    echo "VIRTUAL_DESKTOP  ON"
else
    echo "VIRTUAL_DESKTOP  OFF"
fi

if [ "$(sed -n '/007/p' "${SCRIPTS}/settings")" == "007_FSYNC" ]; then
    export SW_FSYNC=1
    echo "FSYNC  ON"
else
    echo "FSYNC  OFF"
fi

if [ "$(sed -n '/008/p' "${SCRIPTS}/settings")" == "008_ESYNC" ]; then
    export WINEESYNC=1
    echo "ESYNC  ON"
else
    echo "ESYNC  OFF"
fi

if [ "$(sed -n '/009/p' "${SCRIPTS}/settings")" == "009_OLD_GL_STRING" ]; then
    export OLD_GL_STRING=1
    echo "OLD_GL_STRING  ON"
else
    echo "OLD_GL_STRING  OFF"
fi

if [ "$(sed -n '/010/p' "${SCRIPTS}/settings")" == "010_NVAPI_DISABLE" ]; then
    export NVAPI_DISABLE=1
    echo "NVAPI_DISABLE  ON"
else
    echo "NVAPI_DISABLE  OFF"
fi

if [ "$(sed -n '/011/p' "${SCRIPTS}/settings")" == "011_WINEDBG_DISABLE" ]; then
    export WINEDBG_DISABLE=1
    echo "WINEDBG_DISABLE  ON"
else
    echo "WINEDBG_DISABLE  OFF"
fi

if [ "$(sed -n '/012/p' "${SCRIPTS}/settings")" == "012_LARGE_ADDRESS_AWARE" ]; then
    export WINE_LARGE_ADDRESS_AWARE=1
    echo "LARGE_ADDRESS_AWARE  ON"
else
    echo "LARGE_ADDRESS_AWARE  OFF"
fi

if [ "$(sed -n '/013/p' "${SCRIPTS}/settings")" == "013_STAGING_WRITECOPY" ]; then
    export STAGING_WRITECOPY=1
    echo "STAGING_WRITECOPY  ON"
else
    echo "STAGING_WRITECOPY  OFF"
fi

if [ "$(sed -n '/014/p' "${SCRIPTS}/settings")" == "014_STAGING_SHARED_MEMORY" ]; then
    export STAGING_SHARED_MEMORY=1
    echo "STAGING_SHARED_MEMORY  ON"
else
    echo "STAGING_SHARED_MEMORY  OFF"
fi

if [ "$(sed -n '/015/p' "${SCRIPTS}/settings")" == "015_DXVK_HUD" ]; then
    export DXVK_HUD=1
    echo "DXVK_HUD  ON"
else
    echo "DXVK_HUD  OFF"
fi

if [ "$(sed -n '/016/p' "${SCRIPTS}/settings")" == "016_DXVK_ASYNC" ]; then
    export DXVK_ASYNC=1
    echo "DXVK_ASYNC  ON"
else
    echo "DXVK_ASYNC  OFF"
fi

if [ "$(sed -n '/017/p' "${SCRIPTS}/settings")" == "017_VKBASALT" ]; then
    export SW_ENABLE_VKBASALT=1
    echo "VKBASALT  ON"
else
    echo "VKBASALT  OFF"
fi

if [ "$(sed -n '/018/p' "${SCRIPTS}/settings")" == "018_FSR" ]; then
    export SW_FULLSCREEN_FSR=1
    echo "FSR  ON"
else
    echo "FSR  OFF"
fi

if [ "$(sed -n '/019/p' "${SCRIPTS}/settings")" == "019_GSTREAMER" ]; then
    export SW_GSTREAMER=1
    echo "GSTREAMER  ON"
else
    echo "GSTREAMER  OFF"
fi

if [ "$(sed -n '/020/p' "${SCRIPTS}/settings")" == "020_DXVK_GE" ]; then
    export DXVK_GE=1
    echo "DXVK  GE"
else
    echo "DXVK  NATIVE"
fi

if [ "$(sed -n '/021/p' "${SCRIPTS}/settings")" == "021_VKD3D_GE" ]; then
    export VKD3D_GE=1
    echo "VKD3D  GE"
else
    echo "VKD3D  NATIVE"
fi

if [ "$(sed -n '/022/p' "${SCRIPTS}/settings")" == "022_DRI_PRIME" ]; then
    export SW_DRI_PRIME=1
    echo "PRIME  ON"
else
    echo "PRIME  OFF"
fi

if [ "$(sed -n '/024/p' "${SCRIPTS}/settings")" == "024_MONO_ENABLE" ]; then
    export WINE_MONO=1
    echo "WINE_MONO  ON"
else
    export WINE_MONO=0
    echo "WINE_MONO  OFF"
fi

if [ "$(sed -n '/026/p' "${SCRIPTS}/settings")" == "026_BATTLEYE" ]; then
    export SW_BATTLEYE=1
    echo "BATTLEYE  ON"
else
    echo "BATTLEYE  OFF"
fi

if [ "$(sed -n '/027/p' "${SCRIPTS}/settings")" == "027_EASYANTICHEAT" ]; then
    export SW_EASYANTICHEAT=1
    echo "EASYANTICHEAT  ON"
else
    echo "EASYANTICHEAT  OFF"
fi

if [ "$(sed -n '/028/p' "${SCRIPTS}/settings")" == "028_D3D_PLUGINS" ]; then
    export SW_D3D_PLUGINS=1
    echo "D3D_PLUGINS  ON"
else
    echo "D3D_PLUGINS  OFF"
fi

if [ "$(sed -n '/029/p' "${SCRIPTS}/settings")" == "029_VSYNC_DISABLE" ]; then
    export SW_VSYNC_DISABLE=1
    echo "VSYNC_DISABLE  ON"
else
    echo "VSYNC_DISABLE  OFF"
fi

###############################   LOAD GAMES CONFIG   ##########################

export GAMES_CONFIG="${START_WINE_PATH}/data/games_config/${STARTWINE_NAME}"

if [ ! -f "${GAMES_CONFIG}" ]; then

    if [ ! -z "${STARTWINE_NAME}" ]; then
        cat "${START_WINE_PATH}/data/games_config/.default" >> "${START_WINE_PATH}/data/games_config/${STARTWINE_NAME}"
        chmod +x "${START_WINE_PATH}/data/games_config/${STARTWINE_NAME}"
    fi

fi

if [ ! -z "${STARTWINE_NAME}" ]; then

    . "${START_WINE_PATH}/data/games_config/${STARTWINE_NAME}"

fi

###############################   EXPORT   #####################################

export VK_LAYER_PATH="${VK_LAYER_PATH}:${START_WINE_PATH}/data/tools/utils/implicit_layer.d"
export STEAM_COMPAT_CLIENT_INSTALL_PATH="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
export STEAM_COMPAT_DATA_PATH="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
export WINE_MONO_OVERRIDES="Microsoft.Xna.Framework.*,Gac=n"
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_SIZE=1000000000
export __GL_SHADER_DISK_CACHE_PATH="${START_WINE_PATH}/data/tmp"

###############################   AMD + INTEL   ################################

export MESA_GLSL_CACHE_DIR="${START_WINE_PATH}/data/tmp"

################################  CREATE_DIR   #################################

if [ -z "$(find "${START_WINE_PATH}/data" -type d -name "tools" -mtime -"${SW_UPDATE_TIME}" -print 2>/dev/null)" ]; then
    try_remove_dir "${START_WINE_PATH}/data/tools"
fi

create_new_dir "${START_WINE_PATH}/Games"
create_new_dir "${START_WINE_PATH}/data/pfx"
create_new_dir "${START_WINE_PATH}/data/tmp"
create_new_dir "${START_WINE_PATH}/Shortcuts"
create_new_dir "${START_WINE_PATH}/data/tools"
create_new_dir "${START_WINE_PATH}/data/tmp/log"
create_new_dir "${START_WINE_PATH}/data/pfx_backup"
create_new_dir "${START_WINE_PATH}/data/img/favorites"
create_new_dir "/home/${USER}/.local/share/applications"
create_new_dir "${START_WINE_PATH}/data/tools/d3d_extras"

###############################   TOOLS OPTIONS   ##############################

if [ "${SW_HUD_POSITION}" == "R" ]; then
    export HUD_POSITION="right"
else
    export HUD_POSITION="left"
fi

if [ "${SW_MANGOHUD}" == 1 ]; then
    export MANGOHUD=on
    export MANGOHUD_CONFIG="cpu_stats,cpu_temp,core_load,cpu_mhz,cpu_color=2e97cb,cpu_text=CPU,gpu_stats,gpu_temp,gpu_core_clock,gpu_mem_clock,vulkan_driver,gpu_name,gpu_color=2e9762,gpu_text=GPU,vram,vram_color=ad64c1,ram,ram_color=c26693,io_color=a491d3,frame_timing=1,frametime_color=00ff00,time,arch,wine,wine_color=eb5b5b,engine_color=eb5b5b,media_player_color=ffffff,background_alpha=0.2,font_size=20,background_color=020202,position=top-${HUD_POSITION},text_color=ffffff,toggle_hud=Shift_R+F12,media_player_name=spotify,resolution,vkbasalt,gamemode,fps_limit=${SW_FPS_LIMIT},version"
    export SW_HUD="${START_WINE_PATH}/data/tools/utils/bin/mangohud"
else
    export DISABLE_MANGOHUD=on
    if [ "${SW_STRANGLE_FPS_LIMIT}" == 1 ]; then
        export STRANGLE_FPS="${SW_FPS_LIMIT}"
        export STRANGLE_LIB_NAME="libstrangle_vk.so"
        export VK_INSTANCE_LAYERS="${VK_INSTANCE_LAYERS}:SW_VK_LAYER"
    fi
fi

if [ "${RUN_GAMEMODE}" == 1 ]; then
    export SW_GAMEMODE="${START_WINE_PATH}/data/tools/utils/bin/gamemoderun"
fi

if [ "${RUN_RUNTIME}" == 1 ]; then
    export SW_RUNTIME="${START_WINE_PATH}/data/tools/steam-runtime/run.sh"
fi

if [ "${RESTORE_RESOLUTION}" == 1 ]; then
    SCREEN_RESOLUTION="$(xrandr -q | sed -n -e 's/.* connected primary \([^ +]*\).*/\1/p')"
    SCREEN_OUTPUT="$(xrandr -q | sed -n -e 's/\([^ ]*\) connected primary.*/\1/p')"

    if [ -z "${SCREEN_RESOLUTION}" ] || [ -z "${SCREEN_OUTPUT}" ]; then
        SCREEN_RESOLUTION="$(xrandr -q | sed -n -e 's/.* connected \([^ +]*\).*/\1/p')"
        SCREEN_OUTPUT="$(xrandr -q | sed -n -e 's/\([^ ]*\) connected.*/\1/p')"
    fi
fi

if [ "${VIRTUAL_DESKTOP}" == 1 ]; then
    VDESKTOP="explorer /desktop=Wine,`xrandr --current | grep "*" | awk '{print $1;}' | head -1`"
fi

if [ "${SW_FSYNC}" == 1 ]; then
    export WINEFSYNC=1
    export WINEFSYNC_FUTEX2=1
fi

if [ "${OLD_GL_STRING}" == 1 ]; then
    export MESA_EXTENSION_MAX_YEAR="2003"
    export __GL_ExtensionStringVersion="17700"
fi

if [ "${NVAPI_DISABLE}" == 1 ]; then
    var_winedlloverride_update "nvapi,nvapi64,nvcuda,nvcuvid,nvencodeapi,nvencodeapi64="
fi

if [ "${WINEDBG_DISABLE}" == 1 ]; then
    export WINEDEBUG="-all"
    var_winedlloverride_update "winedbg.exe="
fi

if [ "${SW_ENABLE_VKBASALT}" == 1 ]; then
    export ENABLE_VKBASALT=on
    export VKBASALT_CONFIG_FILE="${START_WINE_PATH}/data/vkBasalt.conf"
    export VKBASALT_SHADER_PATH="${START_WINE_PATH}/data/tools/vkBasalt/Shaders"
    export VKBASALT_LOG_FILE="${START_WINE_PATH}/data/tmp/vkBasalt.log"
    sed -i "s%nobody%${START_WINE_PATH}/data/tools%" "${START_WINE_PATH}/data/vkBasalt.conf"
    export VK_INSTANCE_LAYERS="${VK_INSTANCE_LAYERS}:VK_LAYER_VKBASALT_PostProcess64:VK_LAYER_VKBASALT_PostProcess32"
else
    export DISABLE_VKBASALT=on
fi

if [ "${SW_FULLSCREEN_FSR}" == 1 ]; then
    export WINE_FULLSCREEN_FSR=1
    export WINE_FULLSCREEN_FSR_STRENGTH=3
fi

if [ "${SW_GSTREAMER}" == 1 ]; then
    export GST_DEBUG="0:WARNING"
    export WINE_GST_REGISTRY_DIR="${START_WINE_PATH}/data/tmp"
    export MEDIACONV_AUDIO_DUMP_FILE="${START_WINE_PATH}/data/tmp/audio.foz"
    export MEDIACONV_AUDIO_TRANSCODED_FILE="${START_WINE_PATH}/data/tmp/transcoded_audio.foz"
    export MEDIACONV_VIDEO_DUMP_FILE="${START_WINE_PATH}/data/tmp/video.foz"
    export MEDIACONV_VIDEO_TRANSCODED_FILE="${START_WINE_PATH}/data/tmp/transcoded_video.foz"
    export GST_PLUGIN_SYSTEM_PATH_1_0="${WINEDIR}/lib64/gstreamer-1.0:${WINEDIR}/lib/gstreamer-1.0"
fi

if [ "${SW_DRI_PRIME}" == 1 ]; then
    export __NV_PRIME_RENDER_OFFLOAD=1
    export DRI_PRIME=1
fi

if [ "${WINE_MONO}" == 0 ]; then
    var_winedlloverride_update "mscoree,mshtml="
fi

if [ "${SW_BATTLEYE}" == 1 ]; then
    export PROTON_BATTLEYE_RUNTIME="${START_WINE_PATH}/data/tools/Proton_BattlEye_Runtime"
    var_winedlloverride_update "beclient,beclient_x64=b,n"
else
    unset PROTON_BATTLEYE_RUNTIME
fi

if [ "${SW_EASYANTICHEAT}" == 1 ]; then
    export PROTON_EAC_RUNTIME="${START_WINE_PATH}/data/tools/Proton_EasyAntiCheat_Runtime"
    var_winedlloverride_update "easyanticheat_x86,easyanticheat_x64=b,n"
else
    unset PROTON_EAC_RUNTIME
fi

if [ "${SW_VSYNC_DISABLE}" = 1 ]; then
    export vblank_mode=0
    export __GL_SYNC_TO_VBLANK=0
fi

###############################   OVERRIDE DLL   ###############################

var_winedlloverride_update "openvr_api_dxvk,dxvk_config,winemenubuilder.exe="

var_winedlloverride_update "steam_api,steam_api64,steamclient,steamclient64=n"

#var_winedlloverride_update "lsteamclient,GameOverlayRenderer,GameOverlayRenderer64"

var_winedlloverride_update "SteamAppId,SteamGameId="

##############################   RUNTIME DOWNLOAD   ############################

if [ ! -d "${START_WINE_PATH}/data/tools/steam-runtime" ]; then
    export FTP_URL="https://repo.steampowered.com/steamrt-images-scout/snapshots/latest-steam-client-public-beta/steam-runtime.tar.xz"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/steam-runtime.tar.xz"` &&
    crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/steam-runtime.tar.xz" "${START_WINE_PATH}/data/tools"` &&
    try_remove_file "${START_WINE_PATH}/data/tmp/steam-runtime.tar.xz"
    unset LD_LIBRARY_PATH
    sleep 1
    "${START_WINE_PATH}/data/tools/steam-runtime/setup.sh" --force
fi

###############################   DXVK DOWNLOAD   ##############################

if [ ! -d "${START_WINE_PATH}/data/tools/vulkan/dxvk-"${DXVK_VER}"/x64" ]; then
    try_remove_dir "${START_WINE_PATH}/data/tools/vulkan/dxvk-"${DXVK_VER}""
    create_new_dir "${START_WINE_PATH}/data/tools/vulkan/"
    export FTP_URL="https://github.com/doitsujin/dxvk/releases/download/v"${DXVK_VER}"/dxvk-"${DXVK_VER}".tar.gz"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/dxvk-"${DXVK_VER}".tar.gz"` &&
    crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/dxvk-"${DXVK_VER}".tar.gz" "${START_WINE_PATH}/data/tools/vulkan"` &&
    try_remove_file "${START_WINE_PATH}/data/tmp/dxvk-"${DXVK_VER}".tar.gz"
    try_remove_file "${START_WINE_PATH}/data/tools/vulkan/dxvk-"${DXVK_VER}"/setup_dxvk.sh"
fi

###############################   VKD3D DOWNLOAD   #############################

if [ ! -d "${START_WINE_PATH}/data/tools/vulkan/vkd3d-proton-"${VKD3D_VER}"/x64" ]; then
    try_remove_dir "${START_WINE_PATH}/data/tools/vulkan/vkd3d-proton-"${VKD3D_VER}""
    create_new_dir "${START_WINE_PATH}/data/tools/vulkan/"
    export FTP_URL="https://github.com/HansKristian-Work/vkd3d-proton/releases/download/v"${VKD3D_VER}"/vkd3d-proton-"${VKD3D_VER}".tar.zst"
    export DL_NAME="vkd3d-proton-"${VKD3D_VER}""
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/vkd3d-proton-"${VKD3D_VER}".tar.zst"` &&
    unzstd "${START_WINE_PATH}/data/tmp/vkd3d-proton-"${VKD3D_VER}".tar.zst" &&
    crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/vkd3d-proton-"${VKD3D_VER}".tar" "${START_WINE_PATH}/data/tools/vulkan"` &&
    try_remove_file "${START_WINE_PATH}/data/tmp/vkd3d-proton-"${VKD3D_VER}".tar.zst"
    try_remove_file "${START_WINE_PATH}/data/tmp/vkd3d-proton-"${VKD3D_VER}".tar"
    try_remove_file "${START_WINE_PATH}/data/tools/vulkan/vkd3d-proton-"${VKD3D_VER}"/setup_vkd3d_proton.sh"
fi

###############################   VKBASALT DOWNLOAD   ##########################

if [ ! -d "${START_WINE_PATH}/data/tools/vkBasalt/Shaders/" ]; then
    try_remove_dir "${START_WINE_PATH}/data/tools/vkBasalt/"
    create_new_dir "${START_WINE_PATH}/data/tools/vkBasalt/"
    export FTP_URL="https://github.com/crosire/reshade-shaders/archive/master.zip"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/master.zip"` &&
    crier=`$CRIER -zip "${START_WINE_PATH}/data/tmp/master.zip" "${START_WINE_PATH}/data/tmp"` &&
    try_copy_dir "${START_WINE_PATH}/data/tmp/reshade-shaders-master/Textures/" "${START_WINE_PATH}/data/tools/vkBasalt"
    try_copy_dir "${START_WINE_PATH}/data/tmp/reshade-shaders-master/Shaders/" "${START_WINE_PATH}/data/tools/vkBasalt"
    try_remove_file "${START_WINE_PATH}/data/tmp/master.zip"
    try_remove_dir "${START_WINE_PATH}/data/tmp/reshade-shaders-master"
fi

############################   UTILS DOWNLOAD   ################################

if [ ! -d "${START_WINE_PATH}/data/tools/utils/libs" ]; then
    try_remove_dir "${START_WINE_PATH}/data/tools/utils"
    try_remove_file "${START_WINE_PATH}/data/tmp/utils-"${UTILS_VER}".tar.xz"
    export FTP_URL="https://github.com/RusNor/Utils-data/releases/download/utils-"${UTILS_VER}"/utils-"${UTILS_VER}".tar.xz"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/utils-"${UTILS_VER}".tar.xz"` &&
    crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/utils-"${UTILS_VER}".tar.xz" "${START_WINE_PATH}/data/tools"` &&
    try_remove_file "${START_WINE_PATH}/data/tmp/utils-"${UTILS_VER}".tar.xz"

    sed -i "s%nobody%${START_WINE_PATH}/data/tools%" "${START_WINE_PATH}/data/tools/utils/implicit_layer.d/MangoHud.x86.json"
    sed -i "s%nobody%${START_WINE_PATH}/data/tools%" "${START_WINE_PATH}/data/tools/utils/implicit_layer.d/MangoHud.x86_64.json"
    sed -i "s%nobody%${START_WINE_PATH}/data/tools%" "${START_WINE_PATH}/data/tools/utils/implicit_layer.d/vkBasalt32.json"
    sed -i "s%nobody%${START_WINE_PATH}/data/tools%" "${START_WINE_PATH}/data/tools/utils/implicit_layer.d/vkBasalt64.json"
fi

#########################   ANTICHEAT_RUNTIME DOWNLOAD   #######################

if [ ! -d "${START_WINE_PATH}/data/tools/Proton_EasyAntiCheat_Runtime" ]; then
    try_remove_file "${START_WINE_PATH}/data/tmp/AntiCheat_Runtime-${ANTICHEAT_VER}.tar.xz"
    try_remove_dir "${START_WINE_PATH}/data/tmp/AntiCheat_Runtime-${ANTICHEAT_VER}"
    export FTP_URL="https://github.com/RusNor/AntiCheat-Runtime/releases/download/AntiCheat_Runtime-${ANTICHEAT_VER}/AntiCheat_Runtime-${ANTICHEAT_VER}.tar.xz"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/AntiCheat_Runtime-${ANTICHEAT_VER}.tar.xz"` &&
    crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/AntiCheat_Runtime-${ANTICHEAT_VER}.tar.xz" "${START_WINE_PATH}/data/tmp"` &&
    try_copy_dir "${START_WINE_PATH}/data/tmp/AntiCheat_Runtime-${ANTICHEAT_VER}/Proton_BattlEye_Runtime" "${START_WINE_PATH}/data/tools"
    try_copy_dir "${START_WINE_PATH}/data/tmp/AntiCheat_Runtime-${ANTICHEAT_VER}/Proton_EasyAntiCheat_Runtime" "${START_WINE_PATH}/data/tools"
    try_remove_file "${START_WINE_PATH}/data/tmp/AntiCheat_Runtime-${ANTICHEAT_VER}.tar.xz"
    try_remove_dir "${START_WINE_PATH}/data/tmp/AntiCheat_Runtime-${ANTICHEAT_VER}"
fi

###########################   D3D EXTRAS DOWNLOAD   ############################

if [ ! -d "${START_WINE_PATH}/data/tools/d3d_extras/x64" ]; then
    try_remove_dir "${START_WINE_PATH}/data/tools/d3d_extras/x32"
    try_remove_dir "${START_WINE_PATH}/data/tools/d3d_extras/x64"
    try_remove_file "${START_WINE_PATH}/data/tmp/v2.tar.xz"
    export FTP_URL="https://github.com/lutris/d3d_extras/releases/download/v2/v2.tar.xz"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/v2.tar.xz"` &&
    crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/v2.tar.xz" "${START_WINE_PATH}/data/tmp"` &&
    try_copy_dir "${START_WINE_PATH}/data/tmp/v2/x32" "${START_WINE_PATH}/data/tools/d3d_extras"
    try_copy_dir "${START_WINE_PATH}/data/tmp/v2/x64" "${START_WINE_PATH}/data/tools/d3d_extras"
    try_remove_file "${START_WINE_PATH}/data/tmp/v2.tar.xz"
    try_remove_dir "${START_WINE_PATH}/data/tmp/v2"
fi

##############################   RUN VULKAN   ##################################

RUN_VULKAN () {

    ${WINESERVER} -k

    if [ "${USE_OPENGL}" == "1" ]; then

        if [ ! -d "${START_WINE_PATH}/data/pfx/${PFX_GAME}" ]; then
            ${SW_RUNTIME} env "${WINELOADER}" wineboot || prefix_init_error
            "${WINESERVER}" -w

            try_fix_pfx
        fi

        sw_win_ver

        for pfx_remove_dll in d3d12 libvkd3d-proton-utils-3 d3d11 d3d10 d3d10core d3d10_1 d3d9 dxgi ; do
            try_remove_file "${WINEPREFIX}/drive_c/windows/syswow64/${pfx_remove_dll}.dll"
            try_remove_file "${WINEPREFIX}/drive_c/windows/system32/${pfx_remove_dll}.dll"
        done

        if [ "${SW_D3D_PLUGINS}" == 1 ]; then

            for sw_d3d_plugins in d3dcompiler_33 d3dcompiler_34 d3dcompiler_35 d3dcompiler_36 d3dcompiler_37 d3dcompiler_38 d3dcompiler_39 d3dcompiler_40 d3dcompiler_41 d3dcompiler_42 d3dcompiler_43 d3dcompiler_46 d3dcompiler_47 d3dx10_33 d3dx10_34 d3dx10_35 d3dx10_36 d3dx10_37 d3dx10_38 d3dx10_39 d3dx10_40 d3dx10_41 d3dx10_42 d3dx10_43 d3dx10 d3dx11_42 d3dx11_43 d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29 d3dx9_30 d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37 d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43
            do

            if [ "${WINEARCH}" != "win32" ]; then
                try_force_link_file "${START_WINE_PATH}/data/tools/d3d_extras/x64/${sw_d3d_plugins}.dll" "${WINEPREFIX}/drive_c/windows/system32"
                try_force_link_file "${START_WINE_PATH}/data/tools/d3d_extras/x32/${sw_d3d_plugins}.dll" "${WINEPREFIX}/drive_c/windows/syswow64"
            else
                try_force_link_file "${START_WINE_PATH}/data/tools/d3d_extras/x64/${sw_d3d_plugins}.dll" "${WINEPREFIX}/drive_c/windows/system32"
            fi

            var_winedlloverride_update "${sw_d3d_plugins}=n,b"

            done

        fi

        if ! try_copy_file "${WINEDIR}"/lib/wine/fakedlls/dxgi.dll "${WINEPREFIX}/drive_c/windows/syswow64/"; then
            try_copy_file "${WINEDIR}"/lib/wine/i386-windows/dxgi.dll "${WINEPREFIX}/drive_c/windows/syswow64/"
        fi

        if ! try_copy_file "${WINEDIR}"/lib64/wine/fakedlls/dxgi.dll "${WINEPREFIX}/drive_c/windows/system32/"; then
            try_copy_file "${WINEDIR}"/lib64/wine/x86_64-windows/dxgi.dll "${WINEPREFIX}/drive_c/windows/system32/"
        fi

        for wine_build_dll in d3d11 d3d10 d3d10core d3d10_1 d3d9 ; do
        if ! try_copy_file "${WINEDIR}/lib/wine/${wine_build_dll}.dll" "${WINEPREFIX}/drive_c/windows/syswow64/"
            then try_copy_file "${WINEDIR}/lib/wine/i386-windows/${wine_build_dll}.dll" "${WINEPREFIX}/drive_c/windows/syswow64/"
        fi

        if ! try_copy_file "${WINEDIR}/lib64/wine/${wine_build_dll}.dll" "${WINEPREFIX}/drive_c/windows/system32/"; then
            try_copy_file "${WINEDIR}/lib64/wine/x86_64-windows/${wine_build_dll}.dll" "${WINEPREFIX}/drive_c/windows/system32/"
        fi
        done

        var_winedlloverride_update "d3d11,d3d10,d3d10core,d3d10_1,d3d9,dxgi=b;d3d12,libvkd3d-proton-utils-3="

        echo "OpenGL mode"

        notify-send "OpenGL mode"

        START_EXE="$@"
        PATH_TO_GAME="$(dirname "${START_EXE}")"
        cd "${PATH_TO_GAME}"

        ${SW_RUNTIME} env ${SW_GAMEMODE} ${SW_HUD} "${WINELOADER}" ${VDESKTOP} ${WINESTART_EXE} "${START_EXE}" ${LAUNCH_PARAMETERS}

    else

        if [ ! -d "${START_WINE_PATH}/data/pfx/${PFX_GAME}" ]; then
            ${SW_RUNTIME} env "${WINELOADER}" wineboot || prefix_init_error
            "${WINESERVER}" -w

            try_fix_pfx
        fi

        sw_win_ver

        for pfx_remove_dll in d3d12 libvkd3d-proton-utils-3 d3d11 d3d10 d3d10core d3d10_1 d3d9 dxgi ; do
            try_remove_file "${WINEPREFIX}/drive_c/windows/syswow64/${pfx_remove_dll}.dll"
            try_remove_file "${WINEPREFIX}/drive_c/windows/system32/${pfx_remove_dll}.dll"
        done

        if [ "${SW_D3D_PLUGINS}" == 1 ]; then

            for sw_d3d_plugins in d3dcompiler_33 d3dcompiler_34 d3dcompiler_35 d3dcompiler_36 d3dcompiler_37 d3dcompiler_38 d3dcompiler_39 d3dcompiler_40 d3dcompiler_41 d3dcompiler_42 d3dcompiler_43 d3dcompiler_46 d3dcompiler_47 d3dx10_33 d3dx10_34 d3dx10_35 d3dx10_36 d3dx10_37 d3dx10_38 d3dx10_39 d3dx10_40 d3dx10_41 d3dx10_42 d3dx10_43 d3dx10 d3dx11_42 d3dx11_43 d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29 d3dx9_30 d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37 d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43
            do

            if [ "${WINEARCH}" != "win32" ]; then
                try_force_link_file "${START_WINE_PATH}/data/tools/d3d_extras/x64/${sw_d3d_plugins}.dll" "${WINEPREFIX}/drive_c/windows/system32"
                try_force_link_file "${START_WINE_PATH}/data/tools/d3d_extras/x32/${sw_d3d_plugins}.dll" "${WINEPREFIX}/drive_c/windows/syswow64"
            else
                try_force_link_file "${START_WINE_PATH}/data/tools/d3d_extras/x64/${sw_d3d_plugins}.dll" "${WINEPREFIX}/drive_c/windows/system32"
            fi

            var_winedlloverride_update "${sw_d3d_plugins}=n,b"

            done

        fi

        if [ "${DXVK_GE}" == "1" ]; then
            if [ ! -d "${START_WINE_PATH}/data/wine/wine_proton_ge/bin" ]; then
                for wine_dxvk_dll in d3d11 d3d10 d3d10core d3d10_1 d3d9 dxgi ; do
                    try_copy_file "${START_WINE_PATH}/data/tools/vulkan/dxvk-"${DXVK_VER}"/x32/${wine_dxvk_dll}.dll" "${WINEPREFIX}/drive_c/windows/syswow64/"
                    try_copy_file "${START_WINE_PATH}/data/tools/vulkan/dxvk-"${DXVK_VER}"/x64/${wine_dxvk_dll}.dll" "${WINEPREFIX}/drive_c/windows/system32/"
                done
            else
                for wine_dxvk_dll in d3d11 d3d10 d3d10core d3d10_1 d3d9 dxgi ; do
                    try_copy_file "${START_WINE_PATH}/data/wine/wine_proton_ge/lib/wine/dxvk/${wine_dxvk_dll}.dll" "${WINEPREFIX}/drive_c/windows/syswow64/"
                    try_copy_file "${START_WINE_PATH}/data/wine/wine_proton_ge/lib64/wine/dxvk/${wine_dxvk_dll}.dll" "${WINEPREFIX}/drive_c/windows/system32/"
                done
            fi
        else
            for wine_dxvk_dll in d3d11 d3d10 d3d10core d3d10_1 d3d9 dxgi ; do
                try_copy_file "${START_WINE_PATH}/data/tools/vulkan/dxvk-"${DXVK_VER}"/x32/${wine_dxvk_dll}.dll" "${WINEPREFIX}/drive_c/windows/syswow64/"
                try_copy_file "${START_WINE_PATH}/data/tools/vulkan/dxvk-"${DXVK_VER}"/x64/${wine_dxvk_dll}.dll" "${WINEPREFIX}/drive_c/windows/system32/"
            done
        fi

        if [ "${VKD3D_GE}" == "1" ]; then
            if [ ! -d "${START_WINE_PATH}/data/wine/wine_proton_ge/bin" ]; then
                for wine_vkd3d_dll in d3d12 ; do
                    try_copy_file "${START_WINE_PATH}/data/tools/vulkan/vkd3d-proton-"${VKD3D_VER}"/x86/${wine_vkd3d_dll}.dll" "${WINEPREFIX}/drive_c/windows/syswow64/"
                    try_copy_file "${START_WINE_PATH}/data/tools/vulkan/vkd3d-proton-"${VKD3D_VER}"/x64/${wine_vkd3d_dll}.dll" "${WINEPREFIX}/drive_c/windows/system32/"
                done
            else
                for wine_vkd3d_dll in d3d12 libvkd3d-proton-utils-3 ; do
                    try_copy_file "${START_WINE_PATH}/data/wine/wine_proton_ge/lib/wine/vkd3d-proton/${wine_vkd3d_dll}.dll" "${WINEPREFIX}/drive_c/windows/syswow64/"
                    try_copy_file "${START_WINE_PATH}/data/wine/wine_proton_ge/lib64/wine/vkd3d-proton/${wine_vkd3d_dll}.dll" "${WINEPREFIX}/drive_c/windows/system32/"
                done
            fi
        else
            for wine_vkd3d_dll in d3d12 ; do
                try_copy_file "${START_WINE_PATH}/data/tools/vulkan/vkd3d-proton-"${VKD3D_VER}"/x86/${wine_vkd3d_dll}.dll" "${WINEPREFIX}/drive_c/windows/syswow64/"
                try_copy_file "${START_WINE_PATH}/data/tools/vulkan/vkd3d-proton-"${VKD3D_VER}"/x64/${wine_vkd3d_dll}.dll" "${WINEPREFIX}/drive_c/windows/system32/"
            done
        fi

        var_winedlloverride_update "d3d12,libvkd3d-proton-utils-3,d3d11,d3d10,d3d10core,d3d10_1,d3d9,dxgi=n"

        export __GL_DXVK_OPTIMIZATIONS=1
        export DXVK_CONFIG_FILE="${START_WINE_PATH}/data/dxvk.conf"
        export DXVK_STATE_CACHE_PATH="${START_WINE_PATH}/data/tmp/dxvk_cache"
        export DXVK_STATE_CACHE=1
        export DXVK_LOG_LEVEL="none"
        export DXVK_LOG_PATH="none"

        export VKD3D_FEATURE_LEVEL="12_0"
        export VKD3D_SHADER_DEBUG="none"
        export VKD3D_DEBUG="none"

        echo "VULKAN mode"

        notify-send "VULKAN mode"

        START_EXE="$@"
        PATH_TO_GAME="$(dirname "${START_EXE}")"
        cd "${PATH_TO_GAME}"

        ${SW_RUNTIME} env ${SW_GAMEMODE} ${SW_HUD} "${WINELOADER}" ${VDESKTOP} ${WINESTART_EXE} "${START_EXE}" ${LAUNCH_PARAMETERS}

    fi

}

###############################   CREATE SHORTCUT   ############################

CREATE_SHORTCUT () {

    if [ ! -z "${GAME_EXE}" ]; then

        crier=`$CRIER -q "Сreate a new prefix for this game ?"`

        if [ "$(echo $crier)" == "0" ]; then
            export pfx="pfx_"
        else
            export pfx="default_"
        fi

        STARTWINE_EXE="${GAME_EXE}"
        STARTWINE_NAME="$(basename "${STARTWINE_EXE}" | sed 's/\.exe//gi' | sed 's/ /_/g')"
        STARTWINE_PATH="$(cd "$(dirname "${STARTWINE_EXE}")" >/dev/null 2>&1 && pwd)"

        if [ -x "`which wrestool 2>/dev/null`" ]; then
            cd "${STARTWINE_PATH}"
            wrestool -x -t14 "${STARTWINE_EXE}" > "${STARTWINE_EXE}.ico"
            icotool -x "${STARTWINE_EXE}.ico"
            cp "$(ls -S -1 "${STARTWINE_EXE}"*.png | head -n 1)" "${STARTWINE_EXE}.png"
            cp -f "${STARTWINE_EXE}.png" "${START_WINE_PATH}/data/img/${STARTWINE_NAME}.png"
            rm -f "${STARTWINE_PATH}/"*.ico
            rm -f "${STARTWINE_PATH}/"*.png
        fi

            convert -resize 256X256 "${START_WINE_PATH}/data/img/${STARTWINE_NAME}.png" "${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x256.png"
            convert -resize 96X96 "${START_WINE_PATH}/data/img/${STARTWINE_NAME}.png" "${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x96.png"
            rm -f "${START_WINE_PATH}/data/img/${STARTWINE_NAME}.png"

            name_desktop="${STARTWINE_NAME}"
            echo "[Desktop Entry]" > "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "Name=${STARTWINE_NAME}" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "Name_2=${pfx}${STARTWINE_NAME}" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "Exec=env "\"${START_WINE_PATH}/data/scripts/start\" \"${STARTWINE_EXE}\"""\
            >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "Type=Application" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "Categories=Game" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "StartupNotify=true" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "Path="${START_WINE_PATH}/data/scripts/"" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "Icon="${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x256.png"" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            echo "SW_USE=""${SET}" >> "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            chmod +x "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"

        if [ -f "${START_WINE_PATH}/data/wine/wine_custom/${SET}/bin/wine" ]; then
            export WINEDIR="${START_WINE_PATH}/data/wine/wine_custom/${SET}"
            try_remove_steam_lib
            export WINELOADER=$WINEDIR/bin/wine
            cd "${START_WINE_PATH}/data/wine/wine_custom/${SET}/share/wine"
            sed -i '/\AppDefaults\\/g; /HKCU,Software\\Valve\\/g; /HKLM,Software\\Khronos\\/g; /HKLM,Software\\Wow6432Node\\Valve\\Steam/g; /HKCR,steam\\/g' wine.inf
        else
            export WINEDIR="${START_WINE_PATH}/data/wine/${SET}"
            export WINELOADER=$WINEDIR/bin/wine
        fi

        if [ "$(sed -n '3p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop" | sed 's/Name_2=//g' | sed 's/[^pfx_].*//g')" == "pfx_" ]; then
            export PFX_GAME="$(sed -n '3p' "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop" | sed 's/Name_2=//g')"
            export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"

                if [ ! -f "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" ]; then
                    WINEBOOT_CS
                else
                    crier=`$CRIER -q "Restore prefix from backup ?"`

                    if [ "$(echo $crier)" == "0" ]; then
                        if [ "${WINEPREFIX}" != "${START_WINE_PATH}/data/pfx/pfx_default" ]; then
                            try_remove_dir "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
                            cd "${START_WINE_PATH}/data/pfx_backup"
                            unsquashfs "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" &&
                            mv "${START_WINE_PATH}/data/pfx_backup/squashfs-root" "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
                            try_copy_file "${START_WINE_PATH}/data/pfx/${PFX_GAME}/${STARTWINE_NAME}" "${START_WINE_PATH}/data/games_config"
                            try_remove_file "${START_WINE_PATH}/data/pfx/${PFX_GAME}/${STARTWINE_NAME}"
                            crier=`$CRIER -i "Restore prefix completed successfully"`
                        fi
                    else
                         WINEBOOT_CS
                    fi
                fi
        else
            export PFX_GAME="pfx_default"
            export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
            WINEBOOT_CS
        fi
    else
        crier=`$CRIER -i "To create a shortcut run StartWine from the exe file"`
    fi

}

WINEBOOT_CS () {

    ${WINESERVER} -k

    ${SW_RUNTIME} env "${WINELOADER}" wineboot || prefix_init_error
    "${WINESERVER}" -w

    try_fix_pfx

    crier=`$CRIER -q "Would you like to install the recommended libraries ?"`

    if [ "$(echo '$crier')" == "0" ]; then
        INSTALL_RL
    fi

}

ADD_SHORTCUT () {

    if [ ! -f "/home/${USER}/.local/share/applications/${name_desktop}.desktop" ]; then
        try_copy_file "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop" /home/${USER}/.local/share/applications/
        notify-send "Shortcut created in game menu"
    else
        try_remove_file "/home/${USER}/.local/share/applications/${name_desktop}.desktop"
        notify-send "Shortcut removed from game menu"
    fi

}

ADD_FAVORITES () {

    if [ ! -f "${START_WINE_PATH}/data/img/favorites/${name_desktop}.desktop" ]; then
        try_copy_file "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop" "${START_WINE_PATH}/data/img/favorites"
        notify-send "Shortcut added to favorites"
    else
        try_remove_file "${START_WINE_PATH}/data/img/favorites/${name_desktop}.desktop"
        notify-send "Shortcut removed from favorites"
    fi

}

#################################   PREFIX TOOLS   #############################

REMOVE_PFX () {

    crier=`$CRIER -q "Do you really want to remove the prefix ?"`

    if [ "$(echo $crier)" == "0" ]; then

        if [ "${WINEPREFIX}" = "${START_WINE_PATH}/data/pfx/pfx_default" ]; then
            try_remove_file "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            try_remove_file "${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x96.png"
            try_remove_file "${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x256.png"
            try_remove_file "/home/${USER}/.local/share/applications/${name_desktop}.desktop"
            try_remove_file "${START_WINE_PATH}/data/img/favorites/${name_desktop}.desktop"
            notify-send "Shortcut and prefix removed"
        else
            try_remove_dir "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
            try_remove_file "${START_WINE_PATH}/Shortcuts/${name_desktop}.desktop"
            try_remove_file "${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x96.png"
            try_remove_file "${START_WINE_PATH}/data/img/${STARTWINE_NAME}_x256.png"
            try_remove_file "/home/${USER}/.local/share/applications/${name_desktop}.desktop"
            try_remove_file "${START_WINE_PATH}/data/img/favorites/${name_desktop}.desktop"
            notify-send "Shortcut and prefix removed"
        fi

    fi

}

REINSTALL_PFX () {

    if [ ! -f "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" ]; then

        crier=`$CRIER -q "Remove old prefix ?"`

        if [ "$(echo $crier)" == "0" ]; then

            try_remove_dir "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
            WINEBOOT_CS

        fi

    else

        crier=`$CRIER -q "Restore prefix from backup ?"`

        if [ "$(echo $crier)" == "0" ]; then

            if [ "${WINEPREFIX}" != "${START_WINE_PATH}/data/pfx/pfx_default" ]; then
                try_remove_dir "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
                cd "${START_WINE_PATH}/data/pfx_backup"
                unsquashfs "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" &&
                mv "${START_WINE_PATH}/data/pfx_backup/squashfs-root" "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
                try_copy_file "${START_WINE_PATH}/data/pfx/${PFX_GAME}/${STARTWINE_NAME}" "${START_WINE_PATH}/data/games_config"
                try_remove_file "${START_WINE_PATH}/data/pfx/${PFX_GAME}/${STARTWINE_NAME}"
                crier=`$CRIER -i "Restore prefix completed successfully"`
            fi

        else

            crier=`$CRIER -q "Remove old prefix ?"`

            if [ "$(echo $crier)" == "0" ]; then

                try_remove_dir "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
                WINEBOOT_CS

            fi
        fi
    fi

}

SW_PFX_BACKUP () {

    if [ -f "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" ]; then

        crier=`$CRIER -q "Overwrite old backup ?"`

        if [ "$(echo $crier)" == "0" ]; then

            if [ "${WINEPREFIX}" != "${START_WINE_PATH}/data/pfx/pfx_default" ]; then
                try_copy_file "${START_WINE_PATH}/data/games_config/${STARTWINE_NAME}" "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
                try_remove_file "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso"
                mksquashfs "${START_WINE_PATH}/data/pfx/${PFX_GAME}" "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" &&
                try_remove_file "${START_WINE_PATH}/data/pfx/${PFX_GAME}/${STARTWINE_NAME}"
                crier=`$CRIER -i "Backup completed successfully"`
            fi

        fi

    else

        if [ "${WINEPREFIX}" != "${START_WINE_PATH}/data/pfx/pfx_default" ]; then
            try_copy_file "${START_WINE_PATH}/data/games_config/${STARTWINE_NAME}" "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
            try_remove_file "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso"
            mksquashfs "${START_WINE_PATH}/data/pfx/${PFX_GAME}" "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" &&
            try_remove_file "${START_WINE_PATH}/data/pfx/${PFX_GAME}/${STARTWINE_NAME}"
            crier=`$CRIER -i "Backup completed successfully"`
        fi

    fi

}

SW_PFX_RESTORE () {

    if [ ! -f "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" ]; then
        crier=`$CRIER -i "You do not have a backup create it first"`
    else

        if [ "${WINEPREFIX}" != "${START_WINE_PATH}/data/pfx/pfx_default" ]; then
            try_remove_dir "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
            cd "${START_WINE_PATH}/data/pfx_backup"
            unsquashfs "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" &&
            mv "${START_WINE_PATH}/data/pfx_backup/squashfs-root" "${START_WINE_PATH}/data/pfx/${PFX_GAME}"
            try_copy_file "${START_WINE_PATH}/data/pfx/${PFX_GAME}/${STARTWINE_NAME}" "${START_WINE_PATH}/data/games_config"
            try_remove_file "${START_WINE_PATH}/data/pfx/${PFX_GAME}/${STARTWINE_NAME}"
            crier=`$CRIER -i "Restore completed successfully"`
        fi

    fi

}

SW_PFX_FULL_BACKUP () {

    if [ -f "${START_WINE_PATH}/data/pfx_backup/${PFX_GAME}.iso" ]; then

        crier=`$CRIER -q "Overwrite old backup ?"`

        if [ "$(echo $crier)" == "0" ]; then

            try_remove_file "${START_WINE_PATH}/data/pfx_backup/pfx_full_backup.iso"
            mksquashfs "${START_WINE_PATH}/data/pfx" "${START_WINE_PATH}/data/pfx_backup/pfx_full_backup.iso" &&
            crier=`$CRIER -i "Full backup completed successfully"`
        fi

    else

        try_remove_file "${START_WINE_PATH}/data/pfx_backup/pfx_full_backup.iso"
        mksquashfs "${START_WINE_PATH}/data/pfx" "${START_WINE_PATH}/data/pfx_backup/pfx_full_backup.iso" &&
        crier=`$CRIER -i "Full backup completed successfully"`
    fi

}

SW_PFX_FULL_RESTORE () {

    if [ ! -f "${START_WINE_PATH}/data/pfx_backup/pfx_full_backup.iso" ]; then
            crier=`$CRIER -i "You do not have a backup create it first"`
    else
        crier=`$CRIER -q "Would you like to save the current game prefixes ?"`

        if [ "$(echo $crier)" == "0" ]; then

            mv "${START_WINE_PATH}/data/pfx" "${START_WINE_PATH}/data/pfx_old"
            cd "${START_WINE_PATH}/data/pfx_backup"
            unsquashfs "${START_WINE_PATH}/data/pfx_backup/pfx_full_backup.iso" &&
            mv "${START_WINE_PATH}/data/pfx_backup/squashfs-root" "${START_WINE_PATH}/data/pfx"
            crier=`$CRIER -i "Full Restore completed successfully"`
        else
            try_remove_dir "${START_WINE_PATH}/data/pfx"
            cd "${START_WINE_PATH}/data/pfx_backup"
            unsquashfs "${START_WINE_PATH}/data/pfx_backup/pfx_full_backup.iso" &&
            mv "${START_WINE_PATH}/data/pfx_backup/squashfs-root" "${START_WINE_PATH}/data/pfx"
            crier=`$CRIER -i "Full Restore completed successfully"`
        fi

    fi

}

##################################   WINE_TOOLS   ##############################

WINECFG () {

    ${SW_RUNTIME} env "${WINELOADER}" "winecfg"

    try_fix_pfx

}

WINECONSOLE () {

    cd "${START_WINE_PATH}/data/pfx/${PFX_GAME}/drive_c/"
    ${SW_RUNTIME} env "${WINELOADER}" "wineconsole"

    try_fix_pfx

}

REGEDIT () {

    ${SW_RUNTIME} env "${WINELOADER}" "regedit"

    try_fix_pfx

}

WINEFILE () {

    ${SW_RUNTIME} env ${SW_GAMEMODE} "${WINELOADER}" ${VDESKTOP} "explorer"

    try_fix_pfx

}

UNINSTALLER () {

    cd "${START_WINE_PATH}/data/pfx/${PFX_GAME}/drive_c/"
    ${SW_RUNTIME} env "${WINELOADER}" "uninstaller"

    try_fix_pfx

}

SW_WINETRICKS () {

    "${WINESERVER}" -k

    if [ -f "${START_WINE_PATH}"/data/scripts/winetricks ]; then
        rm -f "${START_WINE_PATH}"/data/scripts/winetricks
    fi

    export FTP_URL="https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/scripts/winetricks"` &&
    chmod +x "${START_WINE_PATH}/data/scripts/winetricks"

    export WINE="$WINELOADER"

    "${START_WINE_PATH}/data/scripts/winetricks" -q -f ${DLL} || libraries_init_error
    "${WINESERVER}" -w

    try_fix_pfx


    if [ "${INSTALL_OK}" == 1 ]; then
        crier=`$CRIER -i "Application installed successfully"`
    else
        crier=`$CRIER -i "Libraries installed successfully"`
    fi

}

INSTALL_RL () {

    "${WINESERVER}" -k

    if [ -f "${START_WINE_PATH}"/data/scripts/winetricks ]; then
        rm -f "${START_WINE_PATH}"/data/scripts/winetricks
    fi

    export FTP_URL="https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/scripts/winetricks"` &&
    chmod +x "${START_WINE_PATH}/data/scripts/winetricks"

    export WINE="$WINELOADER"

    "${START_WINE_PATH}/data/scripts/winetricks" -q -f d3dcompiler_42 d3dcompiler_43 d3dcompiler_47 d3dx10 d3dx10_43 d3dx11_42 d3dx11_43 d3dx9 mfc120 mfc42 msvcirt physx vcrun2010 vcrun2012 vcrun2013 vcrun2019 vcrun6 vcrun6sp6 win10 || libraries_init_error
    "${WINESERVER}" -w

    try_fix_pfx

    if [ "${INSTALL_OK}" == 1 ]; then
        crier=`$CRIER -i "Application installed successfully"`
    else
        crier=`$CRIER -i "Libraries installed successfully"`
    fi

}

#################################   DEBUG   ####################################

DEBUG_LOG () {

    export portname="${name_desktop}"
    rm -f  "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "Date and time of start debug for ${portname}" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    date >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "--------------------------------------------------------------------------------------------------" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "Operating system" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    lsb_release -d | sed s/Description/ОС/g >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "--------------------------------------------------------------------------------------------------" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "Desktop Environment" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "$DESKTOP_SESSION" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "${XDG_CURRENT_DESKTOP}" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "--------------------------------------------------------------------------------------------------" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "Kernel" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    uname -r >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "--------------------------------------------------------------------------------------------------" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "CPU" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    cat /proc/cpuinfo | grep "model name" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "--------------------------------------------------------------------------------------------------" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "RAM" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    free -m >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "--------------------------------------------------------------------------------------------------" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "Graphic cards" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    lspci | grep VGA >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    glxinfo | grep OpenGL >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "--------------------------------------------------------------------------------------------------" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "Game name  ${name_desktop}" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "Version WINE" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    "$WINELOADER" --version 2>&1 | tee -a "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "--------------------------------------------------------------------------------------------------" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    echo "log WINE" >> "${START_WINE_PATH}/data/tmp/${portname}.log"
    export WINEDEBUG="fixme-all,err+loaddll,err+dll,err+file,err+reg"

}

DEBUG_VULKAN () {

    DEBUG_LOG

    RUN_VULKAN >> "${START_WINE_PATH}/data/tmp/${portname}.log" 2>&1 "$@"
    crier=`$CRIER -i "Please wait a while then press ok to open the log file"`
    zData=$(cat "${START_WINE_PATH}/data/tmp/${portname}.log")
    crier=`$CRIER -t "${zData}"`

    STOP

}

##############################   DOWNLOAD WINE   ###############################

WINE_1 () {

    try_remove_file "${START_WINE_PATH}/data/tmp/wine-"${STAG_VER}"-staging-amd64.tar.xz" &&
    try_remove_dir "${START_WINE_PATH}/data/tmp/wine-"${STAG_VER}"-staging-amd64"

    if [ ! -d "${START_WINE_PATH}/data/wine/wine_staging/bin" ]; then
        export FTP_URL="https://github.com/Kron4ek/Wine-Builds/releases/download/"${STAG_VER}"/wine-"${STAG_VER}"-staging-amd64.tar.xz"
        crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/wine-"${STAG_VER}"-staging-amd64.tar.xz"`

        crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/wine-"${STAG_VER}"-staging-amd64.tar.xz" "${START_WINE_PATH}/data/tmp"`
        for copy_dir in bin lib share ; do
            try_copy_dir "${START_WINE_PATH}/data/tmp/wine-"${STAG_VER}"-staging-amd64/${copy_dir}" "${START_WINE_PATH}/data/wine/wine_staging"
        done
        try_remove_file "${START_WINE_PATH}/data/tmp/wine-"${STAG_VER}"-staging-amd64.tar.xz" &&
        try_remove_dir "${START_WINE_PATH}/data/tmp/wine-"${STAG_VER}"-staging-amd64"
    fi

    chmod -R 775 "${START_WINE_PATH}/data/wine/wine_staging"

    if [ -d "${START_WINE_PATH}/data/wine/wine_staging/bin" ]; then
        crier=`$CRIER -i "Downloading wine staging completed successfully"`
    else
        crier=`$CRIER -e "Download failed, try again"`
    fi

}

WINE_2 () {

    try_remove_file "${START_WINE_PATH}/data/tmp/steam-proton-"${SP_VER}".tar.xz" &&
    try_remove_dir "${START_WINE_PATH}/data/tmp/steam-proton-"${SP_VER}""

    if [ ! -d "${START_WINE_PATH}/data/wine/wine_steam_proton/bin" ]; then
        export FTP_URL="https://github.com/RusNor/Wine-Steam-Proton/releases/download/steam-proton-"${SP_VER}"/steam-proton-"${SP_VER}".tar.xz"
        crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/steam-proton-"${SP_VER}".tar.xz"` &&

        crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/steam-proton-"${SP_VER}".tar.xz" "${START_WINE_PATH}/data/tmp"` &&
        for copy_dir in bin lib lib64 share ; do
        try_copy_dir "${START_WINE_PATH}/data/tmp/steam-proton-"${SP_VER}"/${copy_dir}" "${START_WINE_PATH}/data/wine/wine_steam_proton"
        done
        try_copy_file "${START_WINE_PATH}/data/tmp/steam-proton-"${SP_VER}"/version" "${START_WINE_PATH}/data/wine/wine_steam_proton" &&
        try_remove_file "${START_WINE_PATH}/data/tmp/steam-proton-"${SP_VER}".tar.xz" &&
        try_remove_dir "${START_WINE_PATH}/data/tmp/steam-proton-"${SP_VER}""
    fi

    chmod -R 775 "${START_WINE_PATH}/data/wine/wine_steam_proton"

    if [ -d "${START_WINE_PATH}/data/wine/wine_steam_proton/bin" ]; then
        crier=`$CRIER -i "Downloading wine steam proton completed successfully"`
    else
        crier=`$CRIER -e "Download failed, try again"`
    fi

}

WINE_3 () {

    try_remove_file "${START_WINE_PATH}/data/tmp/GE-Proton"${GE_VER}".tar.gz" &&
    try_remove_dir "${START_WINE_PATH}/data/tmp/GE-Proton"${GE_VER}""

    if [ ! -d "${START_WINE_PATH}/data/wine/wine_proton_ge/bin" ]; then
        export FTP_URL="https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton"${GE_VER}"/GE-Proton"${GE_VER}".tar.gz"
        crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/GE-Proton"${GE_VER}".tar.gz"` &&

        crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/GE-Proton"${GE_VER}".tar.gz" "${START_WINE_PATH}/data/tmp"` &&
        for copy_dir in bin lib lib64 share ; do
            try_copy_dir "${START_WINE_PATH}/data/tmp/GE-Proton"${GE_VER}"/files/${copy_dir}" "${START_WINE_PATH}/data/wine/wine_proton_ge"
        done
        try_copy_file "${START_WINE_PATH}/data/tmp/GE-Proton"${GE_VER}"/version" "${START_WINE_PATH}/data/wine/wine_proton_ge" &&
        try_remove_file "${START_WINE_PATH}/data/tmp/GE-Proton"${GE_VER}".tar.gz" &&
        try_remove_dir "${START_WINE_PATH}/data/tmp/GE-Proton"${GE_VER}""
    fi

    cd "${START_WINE_PATH}/data/wine/wine_proton_ge/share/wine"
    sed -i '/\AppDefaults\\/g; /HKCU,Software\\Valve\\/g; /HKLM,Software\\Wow6432Node\\Valve\\Steam/g; /HKCR,steam\\/g' wine.inf

    chmod -R 775 "${START_WINE_PATH}/data/wine/wine_proton_ge"

    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"

    try_remove_steam_lib

    if [ -d "${START_WINE_PATH}/data/wine/wine_proton_ge/bin" ]; then
        crier=`$CRIER -i "Downloading wine proton ge completed successfully"`
    else
        crier=`$CRIER -e "Download failed, try again"`
    fi

}

WINE_4 () {

    try_remove_file "${START_WINE_PATH}/data/tmp/wine-lutris-"${LUTRIS_VER}"-x86_64.tar.xz" &&
    try_remove_dir "${START_WINE_PATH}/data/tmp/lutris-"${LUTRIS_VER}"-x86_64"

    if [ ! -d "${START_WINE_PATH}/data/wine/wine_lutris/bin" ]; then
        export FTP_URL="https://github.com/lutris/wine/releases/download/lutris-wine-"${LUTRIS_VER}"/wine-lutris-"${LUTRIS_VER}"-x86_64.tar.xz"
        crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/wine-lutris-"${LUTRIS_VER}"-x86_64.tar.xz"` &&

        crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/wine-lutris-"${LUTRIS_VER}"-x86_64.tar.xz" "${START_WINE_PATH}/data/tmp"` &&
        for copy_dir in bin lib lib64 share ; do
            try_copy_dir "${START_WINE_PATH}/data/tmp/lutris-"${LUTRIS_VER}"-x86_64/${copy_dir}" "${START_WINE_PATH}/data/wine/wine_lutris"
        done
        try_remove_file "${START_WINE_PATH}/data/tmp/wine-lutris-"${LUTRIS_VER}"-x86_64.tar.xz" &&
        try_remove_dir "${START_WINE_PATH}/data/tmp/lutris-"${LUTRIS_VER}"-x86_64"
    fi

    cd "${START_WINE_PATH}/data/wine/wine_lutris/share/wine"
    sed -i '/\AppDefaults\\/g; /HKCU,Software\\Valve\\/g; /HKLM,Software\\Wine/g; /HKLM,Software\\Wow6432Node\\Valve\\Steam/g; /HKCR,steam\\/g' wine.inf

    chmod -R 775 "${START_WINE_PATH}/data/wine/wine_lutris"

    if [ -d "${START_WINE_PATH}/data/wine/wine_lutris/bin" ]; then
        crier=`$CRIER -i "Downloading wine lutris completed successfully"`
    else
        crier=`$CRIER -e "Download failed, try again"`
    fi

}

WINE_5 () {

    try_remove_file "${START_WINE_PATH}/data/tmp/wine-lutris-GE-Proton"${LUTRIS_GE_VER}"-x86_64.tar.xz" &&
    try_remove_dir "${START_WINE_PATH}/data/tmp/lutris-GE-Proton"${LUTRIS_GE_VER}"-x86_64"

    if [ ! -d "${START_WINE_PATH}/data/wine/wine_lutris_ge/bin" ]; then
        export FTP_URL="https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton"${LUTRIS_GE_VER}"/wine-lutris-GE-Proton"${LUTRIS_GE_VER}"-x86_64.tar.xz"
        crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/wine-lutris-GE-Proton"${LUTRIS_GE_VER}"-x86_64.tar.xz"` &&

        crier=`$CRIER -tar "${START_WINE_PATH}/data/tmp/wine-lutris-GE-Proton"${LUTRIS_GE_VER}"-x86_64.tar.xz" "${START_WINE_PATH}/data/tmp"` &&
        for copy_dir in bin lib lib64 share ; do
            try_copy_dir "${START_WINE_PATH}/data/tmp/lutris-GE-Proton"${LUTRIS_GE_VER}"-x86_64/${copy_dir}" "${START_WINE_PATH}/data/wine/wine_lutris_ge"
        done
        try_remove_file "${START_WINE_PATH}/data/tmp/wine-lutris-GE-Proton"${LUTRIS_GE_VER}"-x86_64.tar.xz" &&
        try_remove_dir "${START_WINE_PATH}/data/tmp/lutris-GE-Proton"${LUTRIS_GE_VER}"-x86_64"
    fi

    cd "${START_WINE_PATH}/data/wine/wine_lutris_ge/share/wine"
    sed -i '/\AppDefaults\\/g; /HKCU,Software\\Valve\\/g; /HKLM,Software\\Wine/g; /HKLM,Software\\Wow6432Node\\Valve\\Steam/g; /HKCR,steam\\/g' wine.inf

    chmod -R 775 "${START_WINE_PATH}/data/wine/wine_lutris_ge"

    if [ -d "${START_WINE_PATH}/data/wine/wine_lutris_ge/bin" ]; then
        crier=`$CRIER -i "Downloading wine lutris ge completed successfully"`
    else
        crier=`$CRIER -e "Download failed, try again"`
    fi

}

WINE_6 () {

    xdg-open "${START_WINE_PATH}/data/wine/wine_custom"

}

RM_WINE_1 () {

    try_remove_dir "${START_WINE_PATH}/data/wine/wine_staging"
    create_new_dir "${START_WINE_PATH}/data/wine/wine_staging"

}

RM_WINE_2 () {

    try_remove_dir "${START_WINE_PATH}/data/wine/wine_steam_proton"
    create_new_dir "${START_WINE_PATH}/data/wine/wine_steam_proton"

}

RM_WINE_3 () {

    try_remove_dir "${START_WINE_PATH}/data/wine/wine_proton_ge"
    create_new_dir "${START_WINE_PATH}/data/wine/wine_proton_ge"

}

RM_WINE_4 () {

    try_remove_dir "${START_WINE_PATH}/data/wine/wine_lutris"
    create_new_dir "${START_WINE_PATH}/data/wine/wine_lutris"

}

RM_WINE_5 () {

    try_remove_dir "${START_WINE_PATH}/data/wine/wine_lutris_ge"
    create_new_dir "${START_WINE_PATH}/data/wine/wine_lutris_ge"

}

##################################   STOP   ####################################

STOP () {

    wine_pids="$(ls -l /proc/*/exe 2>/dev/null | grep -ie ${SW_NAME} | grep -E 'wine(64)?-preloader|wineserver' | awk -F/ '{print $3}')"
    if  ! [ -z "${wine_pids}" ]; then
        kill -n 9 ${wine_pids}
    fi

    wine_pids="$(ls -l /proc/*/exe 2>/dev/null | grep -E 'wine(64)?-preloader|wineserver' | awk -F/ '{print $3}')"
    if  ! [ -z "${wine_pids}" ]; then
        kill -n 9 ${wine_pids}
    fi

    notify-send "kill wine porocesses"

    exit

}

#############################   AUTOINSTALL APP   ##############################

INSTALL_BATTLE_NET () {

    export BN_LOC=ruRU || export BN_LOC=enUS
    export FTP_URL="http://dist.blizzard.com/downloads/bna-installers/322d5bb9ae0318de3d4cde7641c96425/retail.1/Battle.net-Setup-${BN_LOC}.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/Battle.net-Setup-${BN_LOC}.exe"`

    export PFX_GAME="pfx_Battle.net"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/Battle.net-Setup-${BN_LOC}.exe" "$@"

    while pgrep -fa 'Battle.net-Setup' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/Program Files (x86)/Battle.net/Battle.net.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/Battle.net-Setup-${BN_LOC}.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_EPIC () {

    export FTP_URL="https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/EpicGamesLauncherInstaller.msi"`

    export PFX_GAME="pfx_EpicGamesLauncher"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/EpicGamesLauncherInstaller.msi" "$@"

    while pgrep -fa 'EpicGamesLauncherInstaller' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/EpicGamesLauncherInstaller.msi"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_EVE () {

    export FTP_URL="https://binaries.eveonline.com/EveLauncher-1892908.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/EveLauncher-1892908.exe"`

    export PFX_GAME="pfx_evelauncher"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/EveLauncher-1892908.exe" /VERYSILENT "$@"

    while pgrep -fa 'EveLauncher-1892908' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/EVE/Launcher/evelauncher.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/EveLauncher-1892908.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_MYGAMES () {

    export FTP_URL="https://static.gc.my.games/MyGamesLoader.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/MyGamesLoader.exe"`

    export PFX_GAME="pfx_GameCenter"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/MyGamesLoader.exe" "$@"

    while pgrep -fa 'MyGamesLoader' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/users/steamuser/AppData/Local/GameCenter/GameCenter.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/MyGamesLoader.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_GOG () {

    export GOG_VER=2.0.46.133
    export FTP_URL="https://content-system.gog.com/open_link/download?path=/open/galaxy/client/${GOG_VER}/setup_galaxy_${GOG_VER}.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/setup_galaxy_${GOG_VER}.exe"`

    export PFX_GAME="pfx_GalaxyClient"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/setup_galaxy_${GOG_VER}.exe" /VERYSILENT "$@"

    while pgrep -fa 'setup_galaxy_${GOG_VER}' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/setup_galaxy_${GOG_VER}.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    export DLL="vcrun2019"
    SW_WINETRICKS

}

INSTALL_LOL () {

    try_remove_file "${START_WINE_PATH}/data/tmp/wine-lutris-ge-7.0-1-lol-x86_64.tar.xz" &&
    try_remove_dir "${START_WINE_PATH}/data/tmp/lutris-ge-7.0-1-lol-x86_64"

    if [ ! -d "${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol/bin" ]; then
        export FTP_URL="https://github.com/GloriousEggroll/wine-ge-custom/releases/download/7.0-GE-1-LoL/wine-lutris-ge-7.0-1-lol-x86_64.tar.xz"
        crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/wine-lutris-ge-7.0-1-lol-x86_64.tar.xz"` &&
        create_new_dir "${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol"
        COPY_BAR () {
        tar -xf "${START_WINE_PATH}/data/tmp/wine-lutris-ge-7.0-1-lol-x86_64.tar.xz" -C "${START_WINE_PATH}/data/tmp" &&
        try_copy_dir "${START_WINE_PATH}/data/tmp/lutris-ge-7.0-1-lol-x86_64/bin" "${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol" &&
        try_copy_dir "${START_WINE_PATH}/data/tmp/lutris-ge-7.0-1-lol-x86_64/lib" "${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol" &&
        try_copy_dir "${START_WINE_PATH}/data/tmp/lutris-ge-7.0-1-lol-x86_64/lib64" "${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol" &&
        try_copy_dir "${START_WINE_PATH}/data/tmp/lutris-ge-7.0-1-lol-x86_64/share" "${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol" &&
        try_remove_file "${START_WINE_PATH}/data/tmp/wine-lutris-ge-7.0-1-lol-x86_64.tar.xz" &&
        try_remove_dir "${START_WINE_PATH}/data/tmp/lutris-ge-7.0-1-lol-x86_64"
        }
        COPY_BAR
    fi

    cd "${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol/share/wine"
    sed -i '/\AppDefaults\\/g; /HKCU,Software\\Valve\\/g; /HKLM,Software\\Wine/g; /HKLM,Software\\Wow6432Node\\Valve\\Steam/g; /HKCR,steam\\/g' wine.inf

    chmod -R 775 "${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol"

    export FTP_URL="https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/live.na.exe"`

    export PFX_GAME="pfx_RiotClientServices"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_custom/lutris-ge-7.0-lol"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/live.na.exe" "$@"

    while pgrep -fa 'live.na.exe' &>/dev/null ; do sleep 1 ; done

    "${WINESERVER}" -k

    SW_USE_EXE="drive_c/Riot Games/Riot Client/RiotClientServices.exe"
    SW_WINE_AUTOINSTALL="lutris-ge-7.0-lol"

    try_remove_file "${START_WINE_PATH}/data/tmp/live.na.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_ORIGIN () {

    export FTP_URL="https://download.dm.origin.com/origin/live/OriginSetup.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/OriginSetup.exe"`

    export PFX_GAME="pfx_Origin"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/OriginSetup.exe" /silent "$@"

    while pgrep -fa 'OriginSetup' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/Program Files (x86)/Origin/Origin.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/OriginSetup.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
#    export DLL="vcrun2019"
#    SW_WINETRICKS

}

INSTALL_ROCKSTAR () {

    export FTP_URL="https://web.archive.org/web/20210708074247if_/https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/Rockstar-Games-Launcher.exe"`

    export PFX_GAME="pfx_Launcher"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/Rockstar-Games-Launcher.exe" /VERYSILENT "$@"

    while pgrep -fa 'Rockstar-Games-Launcher' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/Program Files/Rockstar Games/Launcher/Launcher.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/Rockstar-Games-Launcher.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_STEAM () {

    export FTP_URL="https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/SteamSetup.exe"`

    export PFX_GAME="pfx_steam"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/SteamSetup.exe" /VERYSILENT "$@"

    while pgrep -fa 'SteamSetup' &>/dev/null ; do sleep 1 ; done

    if [ -f "$WINEPREFIX/drive_c/Program Files (x86)/Steam/Steam.exe" ]; then
         mv -f "$WINEPREFIX/drive_c/Program Files (x86)/Steam/Steam.exe" "$WINEPREFIX/drive_c/Program Files (x86)/Steam/steam.exe"
    fi

    SW_USE_EXE="drive_c/Program Files (x86)/Steam/steam.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/SteamSetup.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_UBISOF () {

    export FTP_URL="https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/UbisoftConnectInstaller.exe"`

    export PFX_GAME="pfx_UbisoftConnect"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/UbisoftConnectInstaller.exe" "$@"

    while pgrep -fa 'UbisoftConnectInstaller' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/UbisoftConnect.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/UbisoftConnectInstaller.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_WGC () {

    export WGC_LOC=RU || export WGC_LOC=EU
    export FTP_URL="https://redirect.wargaming.net/WGC/Wargaming_Game_Center_Install_WoT_${WGC_LOC}.exe"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/Wargaming_Game_Center_Install_WoT_${WGC_LOC}.exe"`

    export PFX_GAME="pfx_wgc_api"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/Wargaming_Game_Center_Install_WoT_${WGC_LOC}.exe" "$@"

    while pgrep -fa 'Wargaming_Game_Center_Install_WoT_${WGC_LOC}' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/Program Files (x86)/Wargaming.net/GameCenter/wgc_api/wgc_api.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/Wargaming_Game_Center_Install_WoT_${WGC_LOC}.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

INSTALL_ZONA () {

    export FTP_URL="https://install4.zonastat.com/ZonaSetup.exe?ref=https%3A//www.google.com/"
    crier=`$CRIER -d "${FTP_URL}" "${START_WINE_PATH}/data/tmp/ZonaSetup.exe"`

    export PFX_GAME="pfx_Zona"
    export WINEPREFIX="${START_WINE_PATH}/data/pfx/${PFX_GAME}"
    export WINEDIR="${START_WINE_PATH}/data/wine/wine_proton_ge"
    export WINELOADER=$WINEDIR/bin/wine

    "${WINELOADER}" "${START_WINE_PATH}/data/tmp/ZonaSetup.exe" /silent "$@"

    while pgrep -fa 'ZonaSetup' &>/dev/null ; do sleep 1 ; done

    SW_USE_EXE="drive_c/Program Files (x86)/Zona/Zona.exe"
    SW_WINE_AUTOINSTALL="wine_proton_ge"

    try_remove_file "${START_WINE_PATH}/data/tmp/ZonaSetup.exe"

    sw_shortcuts_autoinstall

    export INSTALL_OK=1
    INSTALL_RL

}

#################################   THE END   ##################################
