#!/usr/bin/env python3

from gettext import gettext as _
import os
import sys
import gi
gi.require_version('AppIndicator3', '0.1')
from gi.repository import AppIndicator3 as appindicator
from gi.repository import Gtk as gtk
from gi.repository import Gdk, GdkPixbuf, Gio, GLib, GObject, Gtk, Pango
from pathlib import Path
import subprocess
from subprocess import *
import threading
import traceback
import logging
import argparse

APPINDICATOR_ID = 'StartWine'

sw_path = f"{Path.home()}/StartWine/"
sw_scripts = f"{Path.home()}/StartWine/data/scripts/"
sw_shortcuts = f"{Path.home()}/StartWine/Shortcuts/"
sw_favorites = f"{Path.home()}/StartWine/data/img/favorites/"
sw_icon = f"{Path.home()}/StartWine/data/img/"
sw_games_config = f"{Path.home()}/StartWine/data/games_config/"
sw_wine_custom = f"{Path.home()}/StartWine/data/wine/wine_custom/"
sw_css_dark = f"{sw_icon}/gui_icons/sw_themes/css/dark/"
sw_css_light = f"{sw_icon}/gui_icons/sw_themes/css/light/"

DIRPATH = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

def main():

    indicator = appindicator.Indicator.new(APPINDICATOR_ID, DIRPATH+"/img/gui_icons/SW_Tray.png", appindicator.IndicatorCategory.APPLICATION_STATUS)
    indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
    indicator.set_menu(menu())
    gtk.main()

def menu():

    menu = gtk.Menu()

##############################   GAME_NAME   ###################################

    def game_name():

        cmd = f"sed 's/\//\\n/g' {sw_scripts}run.sh | sed 's/\"//g' | sed 's/\.exe//gi' | tail -n1"
        proc = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE)
        out = str(proc.stdout[0:])
        out_name = str(out).replace('b\'', 'Open ').strip('n\'').strip('\ ').replace('start', 'StartWine').replace('%F', '')

        print(out_name)

        cmd_one = gtk.MenuItem.new_with_label(str(out_name))
        cmd_one.connect('activate', start_game)
        menu.append(cmd_one)

    game_name()

    cmd_one_1 = gtk.MenuItem.new_with_label('Shortcuts')
    cmd_one_1.connect('activate', shortcuts)
    menu.append(cmd_one_1)

    cmd_one_4 = gtk.MenuItem.new_with_label('Settings')
    cmd_one_4.connect('activate', settings)
    menu.append(cmd_one_4)

    cmd_one_5 = gtk.MenuItem.new_with_label('Stop')
    cmd_one_5.connect('activate', kill)
    menu.append(cmd_one_5)

    exittray = gtk.MenuItem.new_with_label('Exit')
    exittray.connect('activate', quit)
    menu.append(exittray)

    menu.show_all()
    return menu

############################   START GAME   ####################################

def start_game(_):

    cmd = f"{sw_scripts}run.sh"
    subprocess.Popen(cmd, shell=True, start_new_session=True)

############################   SHORTCUTS   #####################################

def shortcuts(_):

    cmd = f"xdg-open '{sw_shortcuts}'"
    subprocess.Popen(cmd, shell=True)

############################   SETTINGS   ######################################

def settings(_):

    def on_btn_settings(self):
        sw_stack.set_visible_child_name("settings_window")

########################   BUTTON_STATE_ON_OFF   ###############################

    def on_dxvk_ge_activated(dxvk_ge):

        if dxvk_ge.get_active():
            state = "on"
            command = f"sed -i '20 s/.*/020_DXVK_GE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/020/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_vkd3d_ge_activated(vkd3d_ge):

        if vkd3d_ge.get_active():
            state = "on"
            command = f"sed -i '21 s/.*/021_VKD3D_GE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/021/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_dxvk_native_activated(dxvk_native):

        if dxvk_native.get_active():
            state = "on"
            command = f"sed -i '20 s/.*/020_DXVK_NATIVE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/020/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_vkd3d_native_activated(vkd3d_native):

        if vkd3d_native.get_active():
            state = "on"
            command = f"sed -i '21 s/.*/021_VKD3D_NATIVE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/021/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_fps_limit_scale(fps_limit_scale):

        fps = fps_limit_scale.get_value()
        command = f"sed -i '25 s/.*/{fps}/' {sw_scripts}settings"
        subprocess.call(command, shell=True)

    def on_DLSYM_activated(DLSYM, gparam):

        if DLSYM.get_active():
            state = "on"
            command = f"sed -i '1 s/.*/001_MANGOHUD_DLSYM/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/001/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_MHUD_activated(MHUD, gparam):

        if MHUD.get_active():
            state = "on"
            command = f"sed -i '2 s/.*/002_MANGOHUD/' {sw_scripts}settings"
            subprocess.run(command, shell=True)
            CompletedProcess(command, returncode=0)
        else:
            state = "off"
            command = f"sed -i '/002/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)
            CompletedProcess(command, returncode=0)

    def on_GAMEMODE_activated(GAMEMODE, gparam):

        if GAMEMODE.get_active():
            state = "on"
            command = f"sed -i '3 s/.*/003_GAMEMODE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/003/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_RUNTIME_activated(RUNTIME, gparam):

        if RUNTIME.get_active():
            state = "on"
            command = f"sed -i '4 s/.*/004_RUNTIME/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/004/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_RESTORE_RESOLUTION_activated(RESTORE_RESOLUTION, gparam):

        if RESTORE_RESOLUTION.get_active():
            state = "on"
            command = f"sed -i '5 s/.*/005_RESTORE_RESOLUTION/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/005/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_VIRTUAL_DESKTOP_activated(VIRTUAL_DESKTOP, gparam):

        if VIRTUAL_DESKTOP.get_active():
            state = "on"
            command = f"sed -i '6 s/.*/006_VIRTUAL_DESKTOP/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/006/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_FSYNC_activated(FSYNC, gparam):

        if FSYNC.get_active():
            state = "on"
            command = f"sed -i '7 s/.*/007_FSYNC/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/007/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_ESYNC_activated(ESYNC, gparam):

        if ESYNC.get_active():
            state = "on"
            command = f"sed -i '8 s/.*/008_ESYNC/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/008/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_OLD_GL_STRING_activated(OLD_GL_STRING, gparam):

        if OLD_GL_STRING.get_active():
            state = "on"
            command = f"sed -i '9 s/.*/009_OLD_GL_STRING/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/009/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_NVAPI_DISABLE_activated(NVAPI_DISABLE, gparam):

        if NVAPI_DISABLE.get_active():
            state = "on"
            command = f"sed -i '10 s/.*/010_NVAPI_DISABLE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/010/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_WINEDBG_DISABLE_activated(WINEDBG_DISABLE, gparam):

        if WINEDBG_DISABLE.get_active():
            state = "on"
            command = f"sed -i '11 s/.*/011_WINEDBG_DISABLE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/011/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_LARGE_ADDRESS_AWARE_activated(LARGE_ADDRESS_AWARE, gparam):

        if LARGE_ADDRESS_AWARE.get_active():
            state = "on"
            command = f"sed -i '12 s/.*/012_LARGE_ADDRESS_AWARE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/012/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_STAGING_WRITECOPY_activated(STAGING_WRITECOPY, gparam):

        if STAGING_WRITECOPY.get_active():
            state = "on"
            command = f"sed -i '13 s/.*/013_STAGING_WRITECOPY/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/013/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_STAGING_SHARED_MEMORY_activated(STAGING_SHARED_MEMORY, gparam):

        if STAGING_SHARED_MEMORY.get_active():
            state = "on"
            command = f"sed -i '14 s/.*/014_STAGING_SHARED_MEMORY/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/014/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_DXVK_HUD_activated(DXVK_HUD, gparam):

        if DXVK_HUD.get_active():
            state = "on"
            command = f"sed -i '15 s/.*/015_DXVK_HUD/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/015/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_DXVK_ASYNC_activated(DXVK_ASYNC, gparam):

        if DXVK_ASYNC.get_active():
            state = "on"
            command = f"sed -i '16 s/.*/016_DXVK_ASYNC/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/016/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_VKBASALT_activated(VKBASALT, gparam):

        if VKBASALT.get_active():
            state = "on"
            command = f"sed -i '17 s/.*/017_VKBASALT/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/017/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_FSR_activated(FSR, gparam):

        if FSR.get_active():
            state = "on"
            command = f"sed -i '18 s/.*/018_FSR/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/018/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_GSTREAMER_activated(GSTREAMER, gparam):

        if GSTREAMER.get_active():
            state = "on"
            command = f"sed -i '19 s/.*/019_GSTREAMER/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/019/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_DRI_PRIME_activated(DRI_PRIME, gparam):

        if DRI_PRIME.get_active():
            state = "on"
            command = f"sed -i '22 s/.*/022_DRI_PRIME/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/022/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_MONO_ENABLE_activated(MONO_ENABLE, gparam):

        if MONO_ENABLE.get_active():

            state = "on"
            command = f"sed -i '24 s/.*/024_MONO_ENABLE/' {sw_scripts}settings"
            subprocess.call(command, shell=True)
        else:
            state = "off"
            command = f"sed -i '/024/g' {sw_scripts}settings"
            subprocess.call(command, shell=True)

    def on_btn_back_st(self):
        cmd = f"cat {sw_scripts}run.sh"
        proc = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE)
        out = str(proc.stdout[0:])
        out_name = str(out).replace('b\'', '').replace('n\'', '').strip('\ ')

        window.close()

        cmd_start = str(out_name)
        subprocess.Popen(cmd_start, shell=True)

#############################   SWITCH BUTTON   ################################

    builder = gtk.Builder()
    builder.add_from_file(f"{sw_scripts}sw_menu.glade")

    window = builder.get_object("StartWine")

    sw_stack = builder.get_object("sw_stack")
    sw_stack.set_transition_type(gtk.StackTransitionType.SLIDE_LEFT_RIGHT)

    sw_stack.set_visible_child_name("settings_window")

    settings_scrolled = builder.get_object("settings_scrolled")
    settings_scrolled.set_min_content_height(580)

    btn_back_st = builder.get_object("btn_back_st")
    btn_back_st.connect("clicked", on_btn_back_st)

    dxvk_ge = builder.get_object("dxvk_ge")
    dxvk_ge.connect("toggled", on_dxvk_ge_activated)

    def dxvk_ge_active():

        dxvk_cmd = f"sed -n '/020/p' {sw_scripts}/settings"
        proc = subprocess.run(dxvk_cmd, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        dxvk_cmd_name = str(proc.stdout[0:]).replace('\n', '')

        if str(dxvk_cmd_name) == str('020_DXVK_GE'):

            dxvk_ge.set_active(True)

        else:

            dxvk_ge.set_active(False)

    dxvk_ge_active()

    vkd3d_ge = builder.get_object("vkd3d_ge")
    vkd3d_ge.connect("toggled", on_vkd3d_ge_activated)

    def vkd3d_ge_active():

        vkd3d_cmd = f"sed -n '/021/p' {sw_scripts}/settings"
        proc = subprocess.run(vkd3d_cmd, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        vkd3d_cmd_name = str(proc.stdout[0:]).replace('\n', '')

        if str(vkd3d_cmd_name) == str('021_VKD3D_GE'):

            vkd3d_ge.set_active(True)

        else:

            vkd3d_ge.set_active(False)

    vkd3d_ge_active()

    dxvk_native = builder.get_object("dxvk_native")
    dxvk_native.connect("toggled", on_dxvk_native_activated)

    def dxvk_native_active():

        dxvk_cmd = f"sed -n '/001/p' {sw_scripts}/settings"
        proc = subprocess.run(dxvk_cmd, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        dxvk_cmd_name = str(proc.stdout[0:]).replace('\n', '')

        if str(dxvk_cmd_name) == str('020_DXVK_NATIVE'):

            dxvk_native.set_active(True)

        else:

            dxvk_native.set_active(False)

    dxvk_native_active()

    vkd3d_native = builder.get_object("vkd3d_native")
    vkd3d_native.connect("toggled", on_vkd3d_native_activated)

    def vkd3d_native_active():

        vkd3d_cmd = f"sed -n '/001/p' {sw_scripts}/settings"
        proc = subprocess.run(vkd3d_cmd, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        vkd3d_cmd_name = str(proc.stdout[0:]).replace('\n', '')

        if str(vkd3d_cmd_name) == str('021_VKD3D_NATIVE'):

            vkd3d_native.set_active(True)

        else:

            vkd3d_native.set_active(False)

    vkd3d_native_active()

    DLSYM = builder.get_object("DLSYM")
    DLSYM.connect("notify::active", on_DLSYM_activated)

    fps_limit_scale = builder.get_object("fps_limit_scale")
    fps_limit_scale.connect("value-changed", on_fps_limit_scale)

    def on_fps_limit(adjustment_fps):

        cmd = f"sed -n '25p' {sw_scripts}/settings"
        proc = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        fps_value = str(proc.stdout[0:]).replace('.0\n', '')

        if str(fps_value) != str(''):
            adjustment_fps.set_value(int(fps_value))

    adjustment_fps = builder.get_object("adjustment_fps")
    adjustment_fps.connect("value-changed", on_fps_limit)

    on_fps_limit(adjustment_fps)

    def dlsym():

        dlsym = f"sed -n '/001/p' {sw_scripts}/settings"
        proc = subprocess.run(dlsym, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        dlsym_name = str(proc.stdout[0:]).replace('\n', '')

        if str(dlsym_name) == str('001_MANGOHUD_DLSYM'):

            DLSYM.set_active(True)

        else:

            DLSYM.set_active(False)

    dlsym()

    MHUD = builder.get_object("MHUD")
    MHUD.connect("notify::active", on_MHUD_activated)

    def mhud():

        mhud = f"sed -n '/002/p' {sw_scripts}/settings"
        proc = subprocess.run(mhud, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        mhud_name = str(proc.stdout[0:]).replace('\n', '')

        if str(mhud_name) == str('002_MANGOHUD'):

            MHUD.set_active(True)

        else:

            MHUD.set_active(False)

    mhud()

    GAMEMODE = builder.get_object("GAMEMODE")
    GAMEMODE.connect("notify::active", on_GAMEMODE_activated)

    def gamemode():

        gamemode = f"sed -n '/003/p' {sw_scripts}/settings"
        proc = subprocess.run(gamemode, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        gamemode_name = str(proc.stdout[0:]).replace('\n', '')

        if str(gamemode_name) == str('003_GAMEMODE'):

            GAMEMODE.set_active(True)

        else:

            GAMEMODE.set_active(False)

    gamemode()

    RUNTIME = builder.get_object("RUNTIME")
    RUNTIME.connect("notify::active", on_RUNTIME_activated)

    def runtime():

        runtime = f"sed -n '/004/p' {sw_scripts}/settings"
        proc = subprocess.run(runtime, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        runtime_name = str(proc.stdout[0:]).replace('\n', '')

        if str(runtime_name) == str('004_RUNTIME'):

            RUNTIME.set_active(True)

        else:

            RUNTIME.set_active(False)

    runtime()

    RESTORE_RESOLUTION = builder.get_object("RESTORE_RESOLUTION")
    RESTORE_RESOLUTION.connect("notify::active", on_RESTORE_RESOLUTION_activated)

    def resres():

        resres = f"sed -n '/005/p' {sw_scripts}/settings"
        proc = subprocess.run(resres, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        resres_name = str(proc.stdout[0:]).replace('\n', '')

        if str(resres_name) == str('005_RESTORE_RESOLUTION'):

            RESTORE_RESOLUTION.set_active(True)

        else:

            RESTORE_RESOLUTION.set_active(False)

    resres()

    VIRTUAL_DESKTOP = builder.get_object("VIRTUAL_DESKTOP")
    VIRTUAL_DESKTOP.connect("notify::active", on_VIRTUAL_DESKTOP_activated)

    def virdesk():

        virdesk = f"sed -n '/006/p' {sw_scripts}/settings"
        proc = subprocess.run(virdesk, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        virdesk_name = str(proc.stdout[0:]).replace('\n', '')

        if str(virdesk_name) == str('006_VIRTUAL_DESKTOP'):

            VIRTUAL_DESKTOP.set_active(True)

        else:

            VIRTUAL_DESKTOP.set_active(False)

    virdesk()

    FSYNC = builder.get_object("FSYNC")
    FSYNC.connect("notify::active", on_FSYNC_activated)

    def fsync():

        fsync = f"sed -n '/007/p' {sw_scripts}/settings"
        proc = subprocess.run(fsync, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        fsync_name = str(proc.stdout[0:]).replace('\n', '')

        if str(fsync_name) == str('007_FSYNC'):

            FSYNC.set_active(True)

        else:

            FSYNC.set_active(False)

    fsync()

    ESYNC = builder.get_object("ESYNC")
    ESYNC.connect("notify::active", on_ESYNC_activated)

    def esync():

        esync = f"sed -n '/008/p' {sw_scripts}/settings"
        proc = subprocess.run(esync, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        esync_name = str(proc.stdout[0:]).replace('\n', '')

        if str(esync_name) == str('008_ESYNC'):

            ESYNC.set_active(True)

        else:

            ESYNC.set_active(False)

    esync()

    OLD_GL_STRING = builder.get_object("OLD_GL_STRING")
    OLD_GL_STRING.connect("notify::active", on_OLD_GL_STRING_activated)

    def glstring():

        glstring = f"sed -n '/009/p' {sw_scripts}/settings"
        proc = subprocess.run(glstring, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        glstring_name = str(proc.stdout[0:]).replace('\n', '')

        if str(glstring_name) == str('009_OLD_GL_STRING'):

            OLD_GL_STRING.set_active(True)

        else:

            OLD_GL_STRING.set_active(False)

    glstring()

    NVAPI_DISABLE = builder.get_object("NVAPI_DISABLE")
    NVAPI_DISABLE.connect("notify::active", on_NVAPI_DISABLE_activated)

    def nvapi():

        nvapi = f"sed -n '/010/p' {sw_scripts}/settings"
        proc = subprocess.run(nvapi, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        nvapi_name = str(proc.stdout[0:]).replace('\n', '')

        if str(nvapi_name) == str('010_NVAPI_DISABLE'):

            NVAPI_DISABLE.set_active(True)

        else:

            NVAPI_DISABLE.set_active(False)

    nvapi()

    WINEDBG_DISABLE = builder.get_object("WINEDBG_DISABLE")
    WINEDBG_DISABLE.connect("notify::active", on_WINEDBG_DISABLE_activated)

    def winedbg():

        winedbg = f"sed -n '/011/p' {sw_scripts}/settings"
        proc = subprocess.run(winedbg, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        winedbg_name = str(proc.stdout[0:]).replace('\n', '')

        if str(winedbg_name) == str('011_WINEDBG_DISABLE'):

            WINEDBG_DISABLE.set_active(True)

        else:

            WINEDBG_DISABLE.set_active(False)

    winedbg()

    LARGE_ADDRESS_AWARE = builder.get_object("LARGE_ADDRESS_AWARE")
    LARGE_ADDRESS_AWARE.connect("notify::active", on_LARGE_ADDRESS_AWARE_activated)

    def large_aa():

        large_aa = f"sed -n '/012/p' {sw_scripts}/settings"
        proc = subprocess.run(large_aa, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        large_aa_name = str(proc.stdout[0:]).replace('\n', '')

        if str(large_aa_name) == str('012_LARGE_ADDRESS_AWARE'):

            LARGE_ADDRESS_AWARE.set_active(True)

        else:

            LARGE_ADDRESS_AWARE.set_active(False)

    large_aa()

    STAGING_WRITECOPY = builder.get_object("STAGING_WRITECOPY")
    STAGING_WRITECOPY.connect("notify::active", on_STAGING_WRITECOPY_activated)

    def staging_w():

        staging_w = f"sed -n '/013/p' {sw_scripts}/settings"
        proc = subprocess.run(staging_w, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        staging_w_name = str(proc.stdout[0:]).replace('\n', '')

        if str(staging_w_name) == str('013_STAGING_WRITECOPY'):

            STAGING_WRITECOPY.set_active(True)

        else:

            STAGING_WRITECOPY.set_active(False)

    staging_w()

    STAGING_SHARED_MEMORY = builder.get_object("STAGING_SHARED_MEMORY")
    STAGING_SHARED_MEMORY.connect("notify::active", on_STAGING_SHARED_MEMORY_activated)

    def staging_s():

        staging_s = f"sed -n '/014/p' {sw_scripts}/settings"
        proc = subprocess.run(staging_s, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        staging_s_name = str(proc.stdout[0:]).replace('\n', '')

        if str(staging_s_name) == str('014_STAGING_SHARED_MEMORY'):

            STAGING_SHARED_MEMORY.set_active(True)

        else:

            STAGING_SHARED_MEMORY.set_active(False)

    staging_s()

    DXVK_HUD = builder.get_object("DXVK_HUD")
    DXVK_HUD.connect("notify::active", on_DXVK_HUD_activated)

    def dxvk_hud():

        dxvk_hud = f"sed -n '/015/p' {sw_scripts}/settings"
        proc = subprocess.run(dxvk_hud, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        dxvk_hud_name = str(proc.stdout[0:]).replace('\n', '')

        if str(dxvk_hud_name) == str('015_DXVK_HUD'):

            DXVK_HUD.set_active(True)

        else:

            DXVK_HUD.set_active(False)

    dxvk_hud()

    DXVK_ASYNC = builder.get_object("DXVK_ASYNC")
    DXVK_ASYNC.connect("notify::active", on_DXVK_ASYNC_activated)

    def dxvk_async():

        dxvk_async = f"sed -n '/016/p' {sw_scripts}/settings"
        proc = subprocess.run(dxvk_async, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        dxvk_async_name = str(proc.stdout[0:]).replace('\n', '')

        if str(dxvk_async_name) == str('016_DXVK_ASYNC'):

            DXVK_ASYNC.set_active(True)

        else:

            DXVK_ASYNC.set_active(False)

    dxvk_async()

    VKBASALT = builder.get_object("VKBASALT")
    VKBASALT.connect("notify::active", on_VKBASALT_activated)

    def vkbasalt():

        vkbasalt = f"sed -n '/017/p' {sw_scripts}/settings"
        proc = subprocess.run(vkbasalt, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        vkbasalt_name = str(proc.stdout[0:]).replace('\n', '')

        if str(vkbasalt_name) == str('017_VKBASALT'):

            VKBASALT.set_active(True)

        else:

            VKBASALT.set_active(False)

    vkbasalt()

    FSR = builder.get_object("FSR")
    FSR.connect("notify::active", on_FSR_activated)

    def fsr():

        fsr = f"sed -n '/018/p' {sw_scripts}/settings"
        proc = subprocess.run(fsr, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        fsr_name = str(proc.stdout[0:]).replace('\n', '')

        if str(fsr_name) == str('018_FSR'):

            FSR.set_active(True)

        else:

            FSR.set_active(False)

    fsr()

    GSTREAMER = builder.get_object("GSTREAMER")
    GSTREAMER.connect("notify::active", on_GSTREAMER_activated)

    def gstreamer():

        gstreamer = f"sed -n '/019/p' {sw_scripts}/settings"
        proc = subprocess.run(gstreamer, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        gstreamer_name = str(proc.stdout[0:]).replace('\n', '')

        if str(gstreamer_name) == str('019_GSTREAMER'):

            GSTREAMER.set_active(True)

        else:

            GSTREAMER.set_active(False)

    gstreamer()

    DRI_PRIME = builder.get_object("DRI_PRIME")
    DRI_PRIME.connect("notify::active", on_DRI_PRIME_activated)

    def dri_prime():

        dri_prime = f"sed -n '/022/p' {sw_scripts}/settings"
        proc = subprocess.run(dri_prime, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        dri_prime_name = str(proc.stdout[0:]).replace('\n', '')

        if str(dri_prime_name) == str('022_DRI_PRIME'):

            DRI_PRIME.set_active(True)

        else:

            DRI_PRIME.set_active(False)

    dri_prime()

    MONO_ENABLE = builder.get_object("MONO_ENABLE")
    MONO_ENABLE.connect("notify::active", on_MONO_ENABLE_activated)

    def mono_enable():

        mono_enable = f"sed -n '/024/p' {sw_scripts}/settings"
        proc = subprocess.run(mono_enable, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
        mono_enable_name = str(proc.stdout[0:]).replace('\n', '')

        if str(mono_enable_name) == str('024_MONO_ENABLE'):

            MONO_ENABLE.set_active(True)

        else:

            MONO_ENABLE.set_active(False)

    mono_enable()

    def get_resolution():

        width = f"xrandr | grep '*' | cut -d 'x' -f1 | sed 's/ //g' | head -n1"
        height = f"xrandr | grep '*' | cut -d 'x' -f2 | cut -d ' ' -f1 | head -n1"
        out_name_1 = str(subprocess.run(width, shell=True, stdout=subprocess.PIPE, encoding='UTF-8').stdout[0:]).replace('\n', '')
        out_name_2 = str(subprocess.run(height, shell=True, stdout=subprocess.PIPE, encoding='UTF-8').stdout[0:]).replace('\n', '')

        print(out_name_1 + "x" + out_name_2)

        def get_css(css_name):

            css = css_name

            screen = Gdk.Screen.get_default()
            provider = Gtk.CssProvider()
            style_context = Gtk.StyleContext()
            style_context.add_provider_for_screen(
                screen, provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
            )
            provider.load_from_path(css)

        def on_btn_black_theme(self):

            if btn_black_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_black_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def black_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_black_theme'):

                css_name = f"{sw_css_dark}black/gtk-3.0/gtk.css"
                get_css(css_name)

                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg1"
                image = builder.get_object("sw_bgr")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("black_theme_off")

        black_theme()

        def on_btn_gray_theme(self):

            if btn_gray_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_gray_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def gray_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_gray_theme'):

                css_name = f"{sw_css_dark}grey/gtk-3.0/gtk.css"
                get_css(css_name)

                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg2"
                image = builder.get_object("sw_bgr")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("gray_theme_off")

        gray_theme()

        def on_btn_red_theme(self):

            if btn_red_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_red_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def red_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_red_theme'):

                css_name = f"{sw_css_dark}red/gtk-3.0/gtk.css"
                get_css(css_name)

                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg3"
                image = builder.get_object("sw_bgr")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("red_theme_off")

        red_theme()

        def on_btn_yellow_theme(self):

            if btn_yellow_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_yellow_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def yellow_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_yellow_theme'):

                css_name = f"{sw_css_dark}yellow/gtk-3.0/gtk.css"
                get_css(css_name)

                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg4"
                image = builder.get_object("sw_bgr")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("yellow_theme_off")

        yellow_theme()

        def on_btn_green_theme(self):

            if btn_green_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_green_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def green_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_green_theme'):

                css_name = f"{sw_css_dark}green/gtk-3.0/gtk.css"
                get_css(css_name)

                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg5"
                image = builder.get_object("sw_bgr")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("green_theme_off")

        green_theme()

        def on_btn_blue_theme(self):

            if btn_blue_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_blue_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def blue_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_blue_theme'):

                css_name = f"{sw_css_dark}blue/gtk-3.0/gtk.css"
                get_css(css_name)

                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg6"
                image = builder.get_object("sw_bgr")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("blue_theme_off")

        blue_theme()

        def on_btn_purple_theme(self):

            if btn_purple_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_purple_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def purple_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_purple_theme'):

                css_name = f"{sw_css_dark}purple/gtk-3.0/gtk.css"
                get_css(css_name)

                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg7"
                image = builder.get_object("sw_bgr")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("purple_theme_off")

        purple_theme()

        def on_btn_mix_theme(self):

            if btn_mix_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_mix_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def mix_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_mix_theme'):

                css_name = f"{sw_css_dark}brown/gtk-3.0/gtk.css"
                get_css(css_name)

                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg8"
                image = builder.get_object("sw_bgr")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("mix_theme_off")

        mix_theme()

        def on_btn_white_theme(self):

            if btn_white_theme.get_active():

                state = "on"
                command = f"sed -i '23 s/.*/023_white_theme/' {sw_scripts}settings"
                subprocess.call(command, shell=True)

                window.close()
                path_game = get_arg(get_path_game())
                cmd = f"{sw_scripts}start {path_game}"
                subprocess.Popen(cmd, shell=True)

            else:

                state = "off"
                command = f"sed -i '/023/g' {sw_scripts}settings"
                subprocess.call(command, shell=True)

        def white_theme():

            sw_theme = f"sed -n '/023/p' {sw_scripts}/settings"
            proc = subprocess.run(sw_theme, shell=True, stdout=subprocess.PIPE, encoding='UTF-8')
            sw_theme_name = str(proc.stdout[0:]).replace('\n', '')

            if str(sw_theme_name) == str('023_white_theme'):

                css_name = f"{sw_css_light}black/gtk-3.0/gtk.css"
                get_css(css_name)
                img_path = f"{sw_icon}gui_icons/sw_themes/4k/sw_bg0"
                image = builder.get_object("sw_bgrw")
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(img_path, int(out_name_1), int(out_name_2), preserve_aspect_ratio=False)
                image.set_from_pixbuf(pixbuf)

            else:

                print("")

        white_theme()

        btn_black_theme = builder.get_object("btn_black_theme")
        btn_black_theme.connect("toggled", on_btn_black_theme)

        btn_gray_theme = builder.get_object("btn_gray_theme")
        btn_gray_theme.connect("toggled", on_btn_gray_theme)

        btn_red_theme = builder.get_object("btn_red_theme")
        btn_red_theme.connect("toggled", on_btn_red_theme)

        btn_yellow_theme = builder.get_object("btn_yellow_theme")
        btn_yellow_theme.connect("toggled", on_btn_yellow_theme)

        btn_green_theme = builder.get_object("btn_green_theme")
        btn_green_theme.connect("toggled", on_btn_green_theme)

        btn_blue_theme = builder.get_object("btn_blue_theme")
        btn_blue_theme.connect("toggled", on_btn_blue_theme)

        btn_purple_theme = builder.get_object("btn_purple_theme")
        btn_purple_theme.connect("toggled", on_btn_purple_theme)

        btn_mix_theme = builder.get_object("btn_mix_theme")
        btn_mix_theme.connect("toggled", on_btn_mix_theme)

        btn_white_theme = builder.get_object("btn_white_theme")
        btn_white_theme.connect("toggled", on_btn_white_theme)

    get_resolution()

    window.connect("destroy", gtk.main_quit)
    window.show_all()

    gtk.main()

###################################   STOP   ###################################

def kill(_):

    cmd = f"{sw_scripts}stop"
    subprocess.call(cmd, shell=True)

def quit(_):

    gtk.main_quit()

if __name__ == "__main__":
    main()
