#!/usr/bin/env bash

###################################___APT___:

if [ -x "$(command -v apt)" ]; then

    sudo apt update -y 2>/dev/null || echo 'Pass' &&
    sudo apt install software-properties-common -y 2>/dev/null || echo 'Pass' &&
    sudo dpkg --add-architecture i386 2>/dev/null || echo 'Pass' &&
    sudo apt update -y 2>/dev/null || echo 'Pass' &&

    for deps in zstd imagemagick vulkan-tools wine ; do

        if [ "`sudo apt list --installed $deps 2>/dev/null | cut -d '/' -f1 | tail -n1`" != "$deps" ]; then
            sudo apt install $deps -y 2>/dev/null || echo "$deps __________Pass"
        else
            echo "$deps"
            echo "_________________________________package is already installed"
        fi

    done

#####################################___DNF___:

elif [ -x "$(command -v dnf)" ]; then

#    sudo dnf update -y || echo 'Pass' &&

    if [ "`sudo dnf list wine | grep @`" == "" ]; then
        sudo dnf install wine -y || echo "$deps ___________________________Pass"
    else
        echo " wine________________________________package is already installed"
    fi

    for deps in zstd ImageMagick vulkan-tools ibus-gtk2.i686 wine32-common ; do

        if [ "`sudo dnf list $deps | grep @`" == "" ]; then
            sudo dnf install $deps -y || echo "$deps ______________________Pass"
        else
            echo "$deps"
            echo "_________________________________package is already installed"
        fi

    done

########################################___ZYPPER___:

elif [ -x "$(command -v zypper)" ]; then

    sudo zypper ref || echo 'Pass' &&

    for deps in zstd ImageMagick vulkan-tools wine ; do

        if [ "`sudo zypper search -i $deps | grep $deps`" == "" ]; then
            sudo zypper in --no-confirm $deps || echo "$deps ______________Pass"
        else
            echo "$deps"
            echo "_________________________________package is already installed"
        fi

    done

########################################___PACMAN___:

elif [ -x "$(command -v pacman)" ]; then

    sudo pacman -Sy -y || echo 'Pass' &&

    for deps in zstd imagemagick python-gobject vulkan-tools ; do

        if [ "`pacman -Qs $deps | grep -w $deps | tail -n1`" == "" ]; then
            sudo pacman -S $deps --noconfirm || echo "$deps _______________Pass"
        else
            echo "$deps"
            echo "_________________________________package is already installed"
        fi

    done

    if [ "`pacman -Qs wine-staging | grep -w wine-staging | tail -n1`" == "" ]; then
        sudo pacman -S --needed wine --noconfirm || echo "$deps ___________Pass"
    else
        echo "wine-staging"
        echo "_________________________________package is already installed"
    fi

########################################___XBPS___:

elif [ -x "$(command -v xbps-install)" ]; then
    sudo xbps-install -Su ||echo 'Pass' &&

    for deps in zstd ImageMagick python-gobject Vulkan-Tools wine ; do

        if [ "`xbps-query -l | awk '{ print $2 }' | xargs -n1 xbps-uhelper getpkgname | grep -w $deps`" = ""]; then
            sudo xbps-install $deps || echo "$deps ___________Pass"
        else
            echo "$deps"
            echo "_________________________________package is already installed"
        fi
    done
else
    echo "FAILED TO INSTALL: Package manager not found. You must manually install"
fi

exit 0

################################################################################
