#!/usr/bin/env python3

"""
Preloading environment variables
"""

import os
import sys
from pathlib import Path
import subprocess
from subprocess import run

#######################___PATHS__:

link = f"{sys.argv[0]}"
sw_scripts = Path(link).parent
sw_path = sw_scripts.parent.parent
sw_tools = Path(f"{sw_path}/data/tools")
sw_main = Path(f"{sw_scripts}/sw_main")
sw_im = Path(f"{sw_scripts}/sw_install_manager")

ld_path = f"{sw_tools}/utils/libs/x86-64"
gi_path = f"{sw_tools}/utils/libs/x86-64/gi_typelib"
os.environ["LD_LIBRARY_PATH"] = os.pathsep + ld_path
os.environ["GI_TYPELIB_PATH"] = os.pathsep + gi_path

################################___START___:

try:
    arg = sys.argv[1]

    if str('--install') in arg:
        run(f"{sw_im}", shell=True)
    else:
        run(f"{sw_main} \"{arg}\"", shell=True)

except IndexError as e:
    print('___set_default_sys_arg___')
    run(f"{sw_main}", shell=True)

